#!/usr/bin/env python3
"""Machine-readable v3.0 slide content for the 207-slide course architecture.

This module is deliberately generator-neutral.  Each slide declares its visual kind,
concise instructional payload, evidence status, and source IDs.  Detailed procedures
remain in the Learner Guide and activity packs.
"""

VERSION = "3.0"
VERSION_DATE = "20 August 2026"
COURSE_CODE = "TGS-2025060473"
TITLE = "AI Security for Autonomous AI Agents"

SOURCES = {
    "S01": {"title": "Turing, Computing Machinery and Intelligence (1950)", "url": "https://academic.oup.com/mind/article/LIX/236/433/986238"},
    "S02": {"title": "Dartmouth Summer Research Project on AI proposal", "url": "http://jmc.stanford.edu/articles/dartmouth/dartmouth.pdf"},
    "S03": {"title": "NIST, Reflections on Artificial Intelligence in Engineering", "url": "https://tsapps.nist.gov/publication/get_pdf.cfm?pub_id=822351"},
    "S04": {"title": "Krizhevsky et al., ImageNet Classification with Deep CNNs", "url": "https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks"},
    "S05": {"title": "Vaswani et al., Attention Is All You Need", "url": "https://arxiv.org/abs/1706.03762"},
    "S06": {"title": "Brown et al., Language Models are Few-Shot Learners", "url": "https://arxiv.org/abs/2005.14165"},
    "S07": {"title": "Ouyang et al., Training language models to follow instructions", "url": "https://arxiv.org/abs/2203.02155"},
    "S08": {"title": "Stanford AI Index Report 2023", "url": "https://hai.stanford.edu/assets/files/hai_ai-index-report_2023.pdf"},
    "S09": {"title": "NIST AI 600-1, Generative AI Profile", "url": "https://www.nist.gov/publications/artificial-intelligence-risk-management-framework-generative-artificial-intelligence"},
    "S10": {"title": "NIST AI Risk Management Framework", "url": "https://www.nist.gov/itl/ai-risk-management-framework"},
    "S11": {"title": "OWASP Top 10 for LLM Applications", "url": "https://genai.owasp.org/llm-top-10/"},
    "S12": {"title": "OWASP Top 10 for Agentic Applications 2026", "url": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/"},
    "S13": {"title": "MITRE ATLAS", "url": "https://atlas.mitre.org/"},
    "S14": {"title": "IMDA Model AI Governance Framework for Agentic AI v1.5 (updated 5 Jun 2026)", "url": "https://www.imda.gov.sg/-/media/imda/files/about/emerging-tech-and-research/artificial-intelligence/mgf-for-agentic-ai.pdf"},
    "S15": {"title": "PDPC Advisory Guidelines on Key Concepts in the PDPA", "url": "https://www.pdpc.gov.sg/guidelines-and-consultation/2020/03/advisory-guidelines-on-key-concepts-in-the-personal-data-protection-act"},
    "S16": {"title": "PDPC Guide on Managing and Notifying Data Breaches", "url": "https://www.pdpc.gov.sg/help-and-resources/2021/05/guide-on-managing-and-notifying-data-breaches-under-the-pdpa"},
    "S17": {"title": "OpenClaw Gateway Security", "url": "https://docs.openclaw.ai/gateway/security"},
    "S18": {"title": "Hermes Agent documentation", "url": "https://hermes-agent.nousresearch.com/docs/"},
    "S19": {"title": "Hermes Agent Security", "url": "https://hermes-agent.nousresearch.com/docs/user-guide/security/"},
    "S20": {"title": "Anthropic — Claude Code sandboxing", "url": "https://www.anthropic.com/engineering/claude-code-sandboxing"},
    "S21": {"title": "OpenAI — Codex sandboxing", "url": "https://learn.chatgpt.com/docs/sandboxing"},
    "S22": {"title": "OpenAI — agent approvals and security", "url": "https://learn.chatgpt.com/docs/agent-approvals-security"},
    "S23": {"title": "DeepSeek-V3 official repository and model card", "url": "https://github.com/deepseek-ai/DeepSeek-V3"},
    "S24": {"title": "Model Context Protocol documentation", "url": "https://modelcontextprotocol.io/docs/getting-started/intro"},
    "S25": {"title": "Aim Labs, EchoLeak research disclosure", "url": "https://www.aim.security/lp/aim-labs-echoleak-blogpost"},
    "S26": {"title": "Invariant Labs, GitHub MCP prompt-injection research", "url": "https://invariantlabs.ai/blog/mcp-github-vulnerability"},
    "S27": {"title": "Moffatt v Air Canada, 2024 BCCRT 149", "url": "https://www.canlii.org/en/bc/bccrt/doc/2024/2024bccrt149/2024bccrt149.html"},
    "S28": {"title": "OpenAI — skills and plugins", "url": "https://learn.chatgpt.com/docs/skills-and-plugins"},
    "S29": {"title": "Anthropic Model Context Protocol overview", "url": "https://docs.anthropic.com/en/docs/mcp"},
    "S30": {"title": "OpenAI — Codex cloud internet access", "url": "https://learn.chatgpt.com/docs/cloud/internet-access"},
    "S31": {"title": "OpenAI — AGENTS.md project instructions", "url": "https://learn.chatgpt.com/docs/agent-configuration/agents-md"},
    "S32": {"title": "OpenAI — ChatGPT Work overview", "url": "https://learn.chatgpt.com/docs/enterprise/chatgpt-work-overview"},
    "S34": {"title": "Prime Intellect — Prime Agent repository and launch documentation", "url": "https://github.com/PrimeIntellect-ai/prime-agent"},
    "S35": {"title": "QM — official repository and security policy", "url": "https://github.com/yc-software/qm/security"},
    "S36": {"title": "DeepSeek Harness — official developer-preview repository", "url": "https://github.com/deepseek-ai/deepseek-harness"},
    "S37": {"title": "Koi Security — ClawHavoc reported malicious-skill campaign", "url": "https://www.koi.ai/blog/clawhavoc-341-malicious-clawedbot-skills-found-by-the-bot-they-were-targeting"},
    "S38": {"title": "AWS Security Bulletin AWS-2025-015", "url": "https://aws.amazon.com/security/security-bulletins/AWS-2025-015/"},
    "S39": {"title": "Replit — application database incident and remediation", "url": "https://replit.com/blog/doubling-down-on-our-commitment-to-secure-vibe-coding"},
    "S40": {"title": "Microsoft — EchoLeak security context", "url": "https://www.microsoft.com/en-us/security/security-insider/emerging-trends/ai-application-security-considerations-for-organizations"},
    "S41": {"title": "MCP authorisation specification (2025-06-18)", "url": "https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization"},
    "S42": {"title": "PDPC proposed GenAI consultation text (2 Jun 2026)", "url": "https://files.app.optical.gov.sg/pdpc/production/assets/6bb79f5a-6f1c-484f-8ed0-91cb64c93abd.pdf"},
    "S43": {"title": "Anthropic — Claude Code permission modes", "url": "https://code.claude.com/docs/en/permission-modes"},
    "S44": {"title": "Anthropic — Claude Code memory and CLAUDE.md", "url": "https://code.claude.com/docs/en/memory"},
    "S45": {"title": "QM — official repository README", "url": "https://github.com/yc-software/qm"},
}


def S(n, kind, title, *, evidence="SYN", sources=(), kicker=None, accent="BLUE",
      points=None, cards=None, headers=None, rows=None, left=None, right=None,
      steps=None, note=None, anchor=None):
    """Return one normalized slide dictionary."""
    d = {
        "n": n, "kind": kind, "title": title, "evidence": evidence,
        "sources": list(sources), "source_urls": [SOURCES[x]["url"] for x in sources],
        "accent": accent,
    }
    for key, value in (("kicker", kicker), ("points", points), ("cards", cards),
                       ("headers", headers), ("rows", rows), ("left", left),
                       ("right", right), ("steps", steps), ("note", note),
                       ("anchor", anchor)):
        if value is not None:
            d[key] = value
    return d


SLIDES = [
    S(1, "cover", TITLE, evidence="ADMIN", kicker=COURSE_CODE,
      points=["Tertiary Infotech Academy Pte Ltd", "Two days · 16 hours", "Version 3.0"]),
    S(2, "attendance", "Digital Attendance — TRAQOM", evidence="ADMIN",
      points=["Scan the LMS QR code", "Complete attendance before class begins", "Ask the trainer if your confirmation is not shown"]),
    S(3, "trainer", "About the Trainer — General", evidence="ADMIN",
      points=["Name and designation", "Qualifications and industry expertise", "Training experience and contact"]),
    S(4, "trainer", "About the Trainer — Dr Alfred Ang", evidence="ADMIN",
      points=["AI and digital-transformation educator", "Technical courseware and applied-agent experience", "Tertiary Infotech Academy"]),
    S(5, "cards", "Who Is in the Room?", evidence="ADMIN",
      cards=[("Role", "What systems do you own or use?"), ("Exposure", "What data and tools can they reach?"), ("Concern", "What outcome would be hardest to reverse?")]),
    S(6, "compare", "Working Agreements for Security Labs", evidence="SYN",
      left=["Synthetic data only", "Local dummy tools", "Share evidence, not secrets"],
      right=["No live credentials", "No real recipients", "No production probing"]),
    S(7, "flow", "Why This Course Exists", evidence="SYN", sources=("S09", "S12", "S14"),
      steps=["Model generates", "Workflow iterates", "Agent receives tools", "Authority creates impact"],
      note="Security changes when probabilistic output can trigger actions in real systems."),
    S(8, "flow", "Two-Day Learning Journey", evidence="ADMIN",
      steps=["Evolution", "System types", "Attack surfaces", "Cases", "Controls", "Governance"]),
    S(9, "cards", "Learning Outcomes", evidence="ADMIN",
      cards=[("LO1", "Explain GenAI concepts and applications"), ("LO2", "Test prompt variations and controls"), ("LO3", "Analyse ethical, bias and security risks")]),
    S(10, "table", "K1–K5 and A1–A5 Evidence Map", evidence="ADMIN",
      headers=["Evidence family", "Statements", "Where demonstrated"],
      rows=[["Models and data", "K1–K3, K5", "History, taxonomy, poisoning"], ["Prompts and metrics", "K4, A5", "Injection activity"], ["Use, limits, ethics", "A1–A4", "Cases and deployment gate"]]),
    S(11, "flow", "Briefing for Assessment", evidence="ADMIN",
      steps=["Read the task", "Use course evidence", "State assumptions", "Justify control choice", "Submit on LMS"]),
    S(12, "compare", "Assessment Components and Boundaries", evidence="ADMIN",
      left=["Written Assessment", "Knowledge statements K1–K5", "Open book"],
      right=["Case Study", "Learning outcomes and abilities", "Evidence-based recommendation"]),
    S(13, "lms", "Courseware, Activities, and Safe Lab Environment", evidence="ADMIN",
      points=["Download current learner-facing files from the LMS", "Use the five activity folders as the evidence workspace", "Run only synthetic, local and reversible tests"]),

    S(14, "section", "Day 1 — From AI Models to Acting Systems", evidence="ADMIN", anchor="day1", accent="VIOLET",
      note="Origins → generation → agency → product anatomy → threat model"),
    S(15, "flow", "The Dependency Map: What Must Be Understood First", evidence="SYN", sources=("S09", "S12", "S14"),
      steps=["What is the system?", "What components does it add?", "What authority does it receive?", "What can fail?", "What evidence controls it?"]),
    S(16, "cards", "Before ‘Generative’: What Did AI Mean?", evidence="DEF", sources=("S10",),
      cards=[("AI system", "Engineered system producing predictions, recommendations, decisions or content"), ("Objective", "Outputs influence virtual or physical environments"), ("Autonomy", "Systems operate with varying levels of autonomy")]),
    S(17, "content", "1950 — The Machine-Intelligence Question", evidence="HIST", sources=("S01",),
      points=["Turing reframed the question through observable conversational behaviour", "The paper discussed learning machines as well as fixed programs", "It predates the term artificial intelligence"]),
    S(18, "content", "1955–1956 — ‘Artificial Intelligence’ Is Named", evidence="HIST", sources=("S02", "S03"),
      points=["The Dartmouth proposal used the term artificial intelligence", "The summer project took place in 1956", "The proposal treated learning and intelligence as problems that could be described precisely"]),
    S(19, "compare", "Symbolic AI and Early Learning Systems", evidence="HIST", sources=("S03",),
      left=["Symbolic systems", "Represent knowledge as rules and symbols", "Reason through explicit operations"],
      right=["Learning systems", "Adjust behaviour from examples or feedback", "Depend on data and objective design"]),
    S(20, "flow", "Cycles of AI Expectation and Investment", evidence="HIST", sources=("S03",),
      steps=["High expectations", "Technical and funding limits", "Reduced investment", "Narrow commercial revival"],
      note="The history is cyclical; avoid a single-cause story for either progress or slowdown."),
    S(21, "flow", "Statistical Machine Learning — Course Synthesis", evidence="SYN", sources=(),
      steps=["Collect examples", "Represent features", "Fit parameters", "Evaluate on held-out data"],
      note="The decision boundary is learned from data rather than authored as a complete rule set."),
    S(22, "content", "2012 — Deep Learning’s Visibility Breakthrough", evidence="HIST", sources=("S04",),
      points=["AlexNet used a deep convolutional network for ImageNet classification", "The published system used GPUs to train the model", "Its result helped demonstrate the practical impact of deep learned representations"]),
    S(23, "compare", "Sequence Models and the Attention Problem", evidence="DEF", sources=("S05",),
      left=["Many earlier neural sequence models", "Recurrence processes tokens in order", "Long dependencies are difficult"],
      right=["Attention", "Weights relationships between positions", "Creates shorter paths between relevant tokens"]),
    S(24, "flow", "2017 — The Transformer", evidence="HIST", sources=("S05",),
      steps=["Token representations", "Self-attention", "Feed-forward layers", "Parallel training"],
      note="The original architecture dispensed with recurrence and convolution for its sequence-transduction tasks."),
    S(25, "cards", "From Large Models to Foundation Models", evidence="DEF", sources=("S09",),
      cards=[("Pre-train", "Learn broad patterns from large, diverse corpora"), ("Adapt", "Prompt, fine-tune or retrieve for a task"), ("Reuse", "One model supports many downstream applications")]),
    S(26, "content", "2020 — Few-Shot Behaviour at Scale", evidence="HIST", sources=("S06",),
      points=["GPT-3 was evaluated on tasks described through text prompts", "Few-shot examples were provided in context rather than through task-specific gradient updates", "Performance varied substantially by task and prompt"]),
    S(27, "flow", "Instruction Following and Human Feedback", evidence="DEF", sources=("S07",),
      steps=["Collect demonstrations", "Train a reward model", "Optimise against preferences", "Evaluate helpfulness and safety"],
      note="Human feedback changes behaviour; it does not create a deterministic policy boundary."),
    S(28, "content", "November 2022 — ChatGPT Broadens the Conversational Interface", evidence="HIST", sources=("S08", "S09"),
      points=["ChatGPT's public release in November 2022 made multi-turn language-model interaction widely visible", "Natural-language prompts exposed many tasks through one interface", "A conversational interface did not remove limitations, variability or data risk"]),
    S(29, "flow", "Retrieval and Tool Use Move Beyond Chat", evidence="SYN", sources=("S09", "S12"),
      steps=["Generate from model knowledge", "Retrieve external context", "Call structured tools", "Iterate toward a goal"],
      note="Each step adds utility and a new trust boundary."),
    S(30, "flow", "The Evolution in One View", evidence="SYN", sources=("S01", "S02", "S05", "S12"),
      steps=["Reason with symbols", "Learn patterns", "Generate content", "Retrieve and use tools", "Plan and act"],
      note="This is an instructional synthesis, not a claim that one paradigm replaced every earlier one."),
    S(31, "break", "Morning Break", evidence="ADMIN", accent="AMBER"),
    S(32, "big", "A Taxonomy Warning: The Terms Are Not Standardised", evidence="DEF", sources=("S09", "S12", "S14"),
      points=["Sources use overlapping labels", "The course declares operational definitions", "Classify the architecture, not the marketing name"], accent="AMBER"),
    S(33, "cards", "Generative AI — Course Definition", evidence="DEF", sources=("S09",),
      cards=[("Primary purpose", "Generate synthetic text, image, audio, video or code"), ("Interaction", "Respond to supplied context and prompts"), ("Boundary", "A model response alone does not imply autonomous action")]),
    S(34, "flow", "How an Autoregressive Language Model Produces Text", evidence="DEF", sources=("S05", "S09"),
      steps=["Tokenise context", "Compute contextual representations", "Estimate next-token probabilities", "Decode the next-token sequence"],
      note="Sampling and context make output probabilistic rather than a fixed database lookup."),
    S(35, "compare", "Generative vs Discriminative Models — Course Comparison", evidence="SYN", sources=("S09",),
      left=["Generative", "Learns patterns used to produce new content", "May be exposed to injection, leakage, poisoning and unsafe output"],
      right=["Discriminative", "Learns to predict a class or score", "May be exposed to poisoning, evasion, leakage and false positives"]),
    S(36, "cards", "Generative AI Strengths", evidence="DEF", sources=("S09",),
      cards=[("Synthesis", "Combine patterns into a new response"), ("Transformation", "Rewrite, translate or structure content"), ("Interface", "Express many tasks in natural language")]),
    S(37, "cards", "Generative AI Weaknesses", evidence="DEF", sources=("S09",),
      cards=[("Confabulation", "Fluent output can be unsupported or wrong"), ("Variability", "Prompt and sampling changes alter results"), ("Provenance", "Output may not reveal which source supported a claim")]),
    S(38, "table", "Generative AI Security Exposure", evidence="DEF", sources=("S09", "S11"),
      headers=["Surface", "Failure", "Impact"], rows=[["Prompt/context", "Instruction hijack", "Wrong or disclosed output"], ["Training/RAG", "Poisoning", "Biased or attacker-shaped answers"], ["Output", "Unsafe downstream handling", "Code, data or browser impact"]]),
    S(39, "cards", "Agentic AI — Course Definition", evidence="DEF", sources=("S12", "S14"),
      cards=[("Goal-directed", "Works toward an objective across steps"), ("Iterative", "Observes results and adjusts"), ("System property", "Agency comes from the model plus orchestration and authority")]),
    S(40, "flow", "The Plan–Act–Observe Loop", evidence="DEF", sources=("S12",),
      steps=["Interpret goal", "Plan next step", "Use tool or act", "Observe result", "Continue or stop"],
      note="A compromised objective can influence every later turn of the loop."),
    S(41, "flow", "Autonomy Is a Spectrum", evidence="DEF", sources=("S14",),
      steps=["Suggest", "Prepare for approval", "Act within hard bounds", "Act broadly with monitoring"],
      note="Risk assessment should set autonomy by impact, reversibility, data sensitivity and tool reach."),
    S(42, "cards", "Agentic AI Strengths", evidence="DEF", sources=("S12", "S14"),
      cards=[("Multi-step work", "Decompose a goal into linked actions"), ("Adaptation", "Use observations to change the plan"), ("Orchestration", "Coordinate models, tools and specialised agents")]),
    S(43, "cards", "Agentic AI Weaknesses", evidence="DEF", sources=("S12",),
      cards=[("Compounding error", "One mistake shapes later observations and plans"), ("Runaway use", "Loops consume time, tokens and tool capacity"), ("Opaque sequence", "A plausible final answer can hide a harmful path")]),
    S(44, "table", "Agentic AI Security Exposure", evidence="DEF", sources=("S12",),
      headers=["Agentic property", "Risk", "Control direction"], rows=[["Goal pursuit", "Goal hijack", "Bind goal and stop conditions"], ["Tool choice", "Tool misuse", "Allowlist and validate"], ["Delegation", "Cascade/inter-agent spoofing", "Authenticate and limit fan-out"]]),
    S(45, "cards", "AI Agent — Course Definition", evidence="DEF", sources=("S12", "S14"),
      cards=[("Concrete system", "A deployed software entity, not just a model"), ("State and observation", "Receives environment feedback and may retain context"), ("Authority", "Acts through tools, identities and policies")]),
    S(46, "cards", "The Agent as a Whole System", evidence="SYN", sources=("S12",),
      cards=[("Mind", "Model, instructions and planning loop"), ("State", "Context, retrieval and memory"), ("Hands", "Tools, identity, runtime and network"), ("Accountability", "Owners, approvers, users and operators")]),
    S(47, "cards", "Instructions and Context", evidence="DEF", sources=("S11", "S12"),
      cards=[("Trusted intent", "System policy and authorised user objective"), ("Untrusted content", "Files, mail, web, tool output and context files"), ("Core weakness", "Selected or retrieved sources can become model-readable context")]),
    S(48, "table", "Retrieval and Memory", evidence="DEF", sources=("S09", "S12"),
      headers=["Layer", "Purpose", "Security concern"], rows=[["Prompt context", "Current turn", "Injection and leakage"], ["RAG corpus", "External knowledge", "Poisoning and access control"], ["Persistent memory", "Cross-session state", "Durable manipulation and privacy"]]),
    S(49, "flow", "Recommended Tool-Execution Path", evidence="SYN", sources=("S12", "S14"),
      steps=["Model proposes intent", "Policy checks identity", "Schema constrains parameters", "Tool executes", "Result is logged"],
      note="The identity and policy layer—not model confidence—defines authority."),
    S(50, "cards", "Runtime, Network, and Feedback", evidence="DEF", sources=("S12",),
      cards=[("Runtime", "Local host, container, VM or managed service"), ("Network", "Inbound channels and outbound destinations"), ("Feedback", "Tool results and environment state become new input")]),
    S(51, "cards", "AI-Agent Strengths", evidence="DEF", sources=("S12",),
      cards=[("Completion", "Carry a task across applications"), ("Optional persistence", "Where configured, resume or schedule work over time"), ("Specialisation", "Delegate subtasks to tools or other agents")]),
    S(52, "cards", "AI-Agent Weaknesses", evidence="DEF", sources=("S12", "S14"),
      cards=[("Blast radius", "Compromise inherits delegated authority"), ("Hidden state", "Memory and intermediate actions complicate review"), ("Responsibility", "Multiple providers and operators can obscure ownership")]),
    S(53, "table", "AI-Agent Security Exposure", evidence="DEF", sources=("S11", "S12"),
      headers=["Axis", "Exposure", "Potential effect"], rows=[["Content", "Injection/jailbreak", "Changed goal or output"], ["Authority", "Token/tool misuse", "Unauthorised action"], ["Runtime", "Code/network/supply chain", "Host impact or exfiltration"], ["State", "Memory poisoning", "Persistent behaviour change"]]),
    S(54, "table", "Three Overlapping Operating Layers", evidence="SYN", sources=("S09", "S12", "S14"),
      headers=["Dimension", "Generative layer", "Agentic pattern", "Deployed agent"], rows=[["Primary role", "Create content", "Pursue goals iteratively", "Operate as a concrete actor"], ["State", "Context-dependent", "Loop state", "May persist memory"], ["Authority", "None inherent", "Configuration-dependent", "Defined by tools and identity"]],
      note="These layers can coexist in one product; they are not mutually exclusive species."),
    S(55, "compare", "Same Model, Different Risk", evidence="SYN", sources=("S09", "S12"),
      left=["Chat configuration", "Reads one prompt", "Returns text", "Human executes any action"],
      right=["Agent configuration", "Reads external sources", "Loops and calls tools", "System executes within delegated authority"]),
    S(56, "flow", "Which Operating Layers Are Present?", evidence="SYN", sources=("S09", "S12", "S14"),
      steps=["Does it mainly generate?", "Does it iterate toward a goal?", "Does it maintain state?", "Can it call tools?", "What authority is delegated?"],
      note="Classify observable architecture and permissions, not the product label."),

    S(57, "section", "Products Are Configurations, Not Risk Labels", evidence="ADMIN", anchor="products", accent="TEAL",
      note="Compare capability, deployment and authority—not brand reputation."),
    S(58, "table", "Examples Across Three Overlapping Layers", evidence="SYN", sources=("S09", "S12"),
      headers=["Operating layer", "Example", "Decisive property"], rows=[["Generative", "Draft or summarise on request", "Returns content"], ["Agentic", "Plan, retry and route tools", "Iterates toward a goal"], ["Deployed agent", "OpenClaw or Hermes deployment", "Concrete runtime with tools and identity"]]),
    S(59, "flow", "Model vs Application vs Harness vs Agent", evidence="DEF", sources=("S09", "S12"),
      steps=["Model generates or scores", "Application supplies context", "Harness orchestrates state/tools", "Agent acts in an environment"],
      note="Model choice alone does not reveal filesystem, network or credential exposure."),
    S(60, "table", "Four Common Deployment Patterns (May Overlap)", evidence="SYN", sources=("S14",),
      headers=["Deployment", "Boundary", "Primary review"], rows=[["Hosted SaaS", "Provider plus tenant controls", "Data terms and workspace settings"], ["Local CLI/desktop", "User account and host", "Filesystem, shell and secrets"], ["Self-hosted gateway", "Organisation runtime", "Network, identity and isolation"], ["Embedded enterprise", "Application and service accounts", "API scopes and transaction controls"]]),
    S(61, "cards", "OpenClaw — Documented Architecture", evidence="PROD", sources=("S17",),
      cards=[("Gateway", "Connects channels, sessions and tools"), ("Host state", "Configuration and credentials live under the runtime state directory"), ("Trust model", "Documentation assumes one trusted operator boundary per gateway")],
      note="As-of 20 Aug 2026; re-check before publication."),
    S(62, "table", "OpenClaw — Documented Security Boundaries", evidence="PROD", sources=("S17",),
      headers=["Boundary", "Documented control", "Residual concern"], rows=[["Senders", "Allowlists and pairing", "Within one trusted-operator boundary, allowed users share delegated authority"], ["Gateway", "Audit and scoped configuration", "Operator credentials are sensitive"], ["Tools", "Deny high-risk tools for untrusted content", "Node execution can affect a paired host"]],
      note="As of 20 Aug 2026; controls depend on the gateway, channel, tools and host configuration."),
    S(63, "cards", "Hermes Agent — Documented Architecture", evidence="PROD", sources=("S18",),
      cards=[("Entry points", "CLI, gateway, API and library modes"), ("State", "Persistent memory, skills and project context"), ("Authority", "Built-in tools, MCP and multiple execution backends")],
      note="As-of 20 Aug 2026; re-check before publication."),
    S(64, "table", "Hermes Agent — Documented Security Layers", evidence="PROD", sources=("S19",),
      headers=["Layer", "Purpose", "Example"], rows=[["Authorisation", "Control who can interact", "Allowlist and DM pairing"], ["Execution", "Constrain dangerous operations", "Approval and container isolation"], ["Context", "Reduce malicious project instructions", "Context-file scanning"]],
      note="As of 20 Aug 2026; permanent approvals, permissive modes and execution backend alter exposure."),
    S(65, "cards", "Claude Code — Capability and Authority Profile", evidence="PROD", sources=("S20", "S29", "S43"),
      cards=[("Local context", "Reads project files within configured access"), ("Tools", "Terminal and MCP expand capability"), ("Permissions", "Allowed/disallowed tools and permission modes affect authority")],
      note="As of 20 Aug 2026; sandbox and permission mode are configuration-specific. A bypass flag is not a recommended default."),
    S(66, "cards", "Codex — Capability Depends on Surface and Mode", evidence="PROD", sources=("S21", "S22", "S30"),
      cards=[("Workspace", "Supported local configurations can bound writes to an authorised workspace"), ("Approval", "Access outside the boundary or consequential actions can require approval"), ("Network", "Cloud internet access is separately configurable and changes injection and exfiltration exposure")],
      note="As-of 20 Aug 2026; cite the exact deployed Codex surface and settings."),
    S(67, "compare", "ChatGPT Chat and ChatGPT Work — Current Surfaces", evidence="PROD", sources=("S22", "S28", "S32"),
      left=["Chat", "Conversational exploration and generation", "Authority depends on enabled tools and context"],
      right=["Work", "Supports multi-step work with authorised files, apps and tools", "Local/cloud surface, member permissions and admin policy define the boundary"],
      note="As of 20 Aug 2026; feature availability and authority depend on plan, workspace and enabled tools."),
    S(68, "cards", "DeepSeek Model vs DeepSeek Harness", evidence="PROD", sources=("S23", "S36"),
      cards=[("DeepSeek-V3 model", "Model card describes weights and inference; it does not define host authority"), ("DeepSeek Harness", "Official repository labels dsh a developer preview with plugin-oriented architecture"), ("Security decision", "Treat production controls as unknown until the exact version and configuration are verified")],
      note="As of 20 Aug 2026; model and harness are different layers. Do not import permissions or sandbox claims from one to the other."),
    S(69, "cards", "Prime Agent and QM — Documented Boundaries", evidence="PROD", sources=("S34", "S35", "S45"),
      cards=[("Prime Agent", "Persistent coding/research harness; its documentation says the kernel is not a security sandbox"), ("QM", "Early organisational-agent harness with durable sandboxes, memory, skills and documented security limitations"), ("Deployment gate", "Verify exact version, host, command posture, egress, credentials and external containment")],
      note="As of 20 Aug 2026; first-party documentation describes capabilities and limitations, not independent assurance or a safety ranking."),
    S(70, "table", "Eight Products — Runtime and Review Focus", evidence="PROD", sources=("S17", "S18", "S20", "S21", "S22", "S32", "S34", "S35", "S36", "S45"),
      headers=["Product", "Documented runtime emphasis", "Primary review"], rows=[["OpenClaw", "Self-hosted gateway, channels and tools", "Trusted operator, host and tool policy"], ["Hermes", "CLI/gateway/API with selectable execution backends", "Approvals, backend, memory and MCP"], ["Prime Agent", "Persistent Python, skills, subagents and schedules", "External isolation and user OS permissions"], ["QM", "Organisational harness with durable scoped sandboxes", "Permission mode, keys and egress"], ["DeepSeek Harness", "Developer-preview plugin harness", "Exact commit, plugins, listener and host"], ["Claude Code", "Repository-aware coding agent", "Sandbox, terminal/MCP and permission mode"], ["Codex", "Local and cloud surfaces", "Workspace, approval and network mode"], ["ChatGPT / Work", "Chat plus authorised files/apps/tools", "Local/cloud surface and admin policy"]],
      note="As of 20 Aug 2026; documented capability is not a safety score."),
    S(71, "compare", "OpenClaw vs Hermes — Gateway and Execution", evidence="PROD", sources=("S17", "S18", "S19"),
      left=["OpenClaw", "One trusted-operator gateway boundary", "Channels, tools, nodes and runtime state", "Sandboxing and exposure depend on configuration"],
      right=["Hermes", "CLI, gateway, API and library entry points", "Memory, skills, MCP and multiple execution backends", "Approvals and backend choice change authority"],
      note="As of 20 Aug 2026; compare deployments, not brand names."),
    S(72, "compare", "Prime Agent vs QM — Persistence and Permission", evidence="PROD", sources=("S34", "S35", "S45"),
      left=["Prime Agent", "Persistent Python, subagents and schedules", "Model-generated Python and commands execute with the launching user's OS permissions", "Kernel is not a security sandbox"],
      right=["QM", "Durable per-scope sandbox, memory and files", "Strict, Auto and Dangerous permission modes", "Early software with documented limitations"],
      note="As of 20 Aug 2026; external containment and selected mode are part of the risk decision."),
    S(73, "compare", "DeepSeek Harness vs Claude Code — Plugin and Repository Boundary", evidence="PROD", sources=("S20", "S29", "S36"),
      left=["DeepSeek Harness (dsh)", "Official developer preview", "Plugin-oriented harness and local UI", "Production control baseline not verified"],
      right=["Claude Code", "Repository-aware coding workflow", "Terminal and MCP capability", "Sandbox and permission mode affect authority"],
      note="As of 20 Aug 2026; assess the exact version and enabled extensions."),
    S(74, "compare", "Codex vs ChatGPT Work — Workspace and Tool Authority", evidence="PROD", sources=("S21", "S22", "S30", "S32"),
      left=["Codex", "Local/cloud coding surfaces", "Workspace sandbox and approvals vary by mode", "Internet access is separately configurable"],
      right=["ChatGPT Work", "Multi-step local/cloud work", "Uses authorised files, apps and tools", "Member permissions and admin policy shape effects"],
      note="As of 20 Aug 2026; state the product surface and mode before comparing risk."),
    S(75, "table", "Extension and Persistence Questions Across All Eight", evidence="SYN", sources=("S17", "S18", "S28", "S29", "S34", "S35", "S36", "S45"),
      headers=["Axis", "What to verify", "Why it matters"], rows=[["Skills/plugins/MCP", "Publisher, code, instructions, scopes and update channel", "Extensions can add data and action paths"], ["Memory/schedules", "Where supported, provenance, retention and revocation", "State can outlive the initiating turn"], ["Credentials", "Identity, scope, lifetime and storage", "Compromise inherits delegated authority"], ["Network", "Inbound triggers and outbound destinations", "Reach defines trigger and exfiltration paths"]],
      note="Not documented means unknown—not absent."),
    S(76, "flow", "Product Evidence Gate Before Deployment", evidence="SYN", sources=("S14",),
      steps=["Pin product/version", "Name runtime and host", "Inventory data/tools", "Verify approval/logging", "Record unknowns and re-test"],
      note="Re-check documentation at change or publication; no product receives a universal green/red score."),
    S(77, "flow", "Select by Use Case and Risk Tier", evidence="SYN", sources=("S10", "S14"),
      steps=["Classify impact", "Classify data", "Identify actions", "Assess reversibility", "Choose bounded deployment"],
      note="A higher-capability product is acceptable only when its authority and evidence fit the risk."),
    S(78, "break", "Lunch Break", evidence="ADMIN", accent="AMBER"),

    S(79, "section", "Threat Modelling AI Systems", evidence="ADMIN", anchor="threat_model", accent="RED",
      note="Follow content to authority, effect and evidence."),
    S(80, "cards", "Classical Security Still Applies", evidence="DEF", sources=("S10", "S13"),
      cards=[("Identity", "Authenticate users, services and agents"), ("Systems", "Patch, segment and harden hosts"), ("Operations", "Log, detect, respond and recover")]),
    S(81, "compare", "What AI Adds or Amplifies", evidence="DEF", sources=("S09", "S11", "S12"),
      left=["Conventional", "Software vulnerabilities", "Credential theft", "Supply-chain compromise"],
      right=["AI-specific/amplified", "Instruction/data confusion", "Poisoned context and memory", "Probabilistic plans driving tools"]),
    S(82, "cards", "Threat Actors and Their Access Paths", evidence="SYN", sources=("S13",),
      cards=[("External", "Users, senders and web publishers"), ("Internal", "Staff, admins and data curators"), ("Supply chain", "Model, plugin, skill, MCP and package publishers")]),
    S(83, "cards", "Assets Worth Protecting", evidence="SYN", sources=("S09", "S14", "S15"),
      cards=[("Data", "Personal data, prompts, files, memory and logs"), ("Authority", "Tokens, permissions, tools and approvals"), ("Decisions", "Outputs, actions, provenance and audit evidence")]),
    S(84, "flow", "Trust Boundaries in a GenAI Application", evidence="DEF", sources=("S09", "S11"),
      steps=["User/channel", "Application", "Model provider", "Retrieval source", "Output consumer"],
      note="Annotate who controls each boundary and which data crosses it."),
    S(85, "flow", "Trust Boundaries in an AI Agent", evidence="DEF", sources=("S12",),
      steps=["Untrusted content", "Planner and memory", "Policy/identity", "Tool/runtime", "Network/environment"],
      note="The agent adds persistent state and action paths to the model boundary."),
    S(86, "cards", "Treat Every Content Source as Untrusted", evidence="SYN", sources=("S11", "S12", "S17", "S19"),
      cards=[("Human content", "Prompts, email, chat and documents"), ("Machine content", "Web, APIs and tool output"), ("Project content", "Memory, context files, skills, plugins and MCP metadata")]),
    S(87, "flow", "Follow the Authority Path", evidence="SYN", sources=("S12", "S14"),
      steps=["Attacker controls content", "Model interprets", "Planner selects action", "Policy permits", "Tool creates effect"],
      note="Break the path with deterministic controls as close to the effect as possible."),
    S(88, "flow", "Threat-Modelling Method", evidence="SYN", sources=("S10", "S13", "S14"),
      steps=["Scope use case", "Map data and components", "Mark trust boundaries", "Write abuse cases", "Select and test controls"]),
    S(89, "table", "Attack Surface by Operating Layer", evidence="SYN", sources=("S09", "S11", "S12"),
      headers=["Surface", "Generative", "Agentic", "Agent"], rows=[["Input", "Prompt/context", "Goal and observations", "Channels, files, web"], ["State", "Context window", "Loop state", "RAG and persistent memory"], ["Effect", "Output", "Plan/tool selection", "Real system action"]]),
    S(90, "flow", "A Complete Attack Chain", evidence="SYN", sources=("S12", "S13"),
      steps=["Deliver", "Interpret", "Plan", "Authorise", "Execute", "Persist", "Impact"],
      note="Record evidence and a feasible control at every stage."),
    S(91, "activity", "Activity 1 — Concierge Threat Model", evidence="SIM", accent="BLUE",
      points=["Map three input channels, four retrieval sources and four tools", "Mark attacker-writable content and personal-data paths", "Recommend proceed, conditional proceed or halt"]),
    S(92, "activity", "Activity 1 — Build the Data-Flow Diagram", evidence="SIM",
      points=["Place channels and data owners on the left", "Put model, retrieval and memory in the centre", "Put tool actions and affected people on the right"]),
    S(93, "activity", "Activity 1 — Rank Trust Boundaries", evidence="SIM",
      points=["Who can write the source?", "What authority can follow from it?", "How reversible is the effect?"]),
    S(94, "activity", "Activity 1 — Design Abuse Cases", evidence="SIM",
      points=["One GenAI content failure", "One agentic loop or goal failure", "One tool/identity action failure"]),
    S(95, "activity", "Activity 1 — Decide the Controls", evidence="SIM",
      points=["Rank controls by earliest break point", "State latency, cost and user-friction trade-offs", "Name evidence proving each control works"]),
    S(96, "table", "Day 1 Integrated Risk Matrix", evidence="SYN", sources=("S09", "S11", "S12", "S14"),
      headers=["System", "Primary exposure", "Control direction"], rows=[["Generative", "Content and disclosure", "Constrain data access and downstream effect; validate before use"], ["Agentic", "Goal and loop", "Stop conditions and budgets"], ["Agent", "Tools, identity, runtime", "Least privilege, sandbox and approval"]]),
    S(97, "cards", "Day 1 Recap — What Changed as AI Gained Agency?", evidence="SYN", sources=("S09", "S12", "S14"),
      cards=[("Generate", "Probability creates useful but fallible content"), ("Iterate", "Loops compound decisions and cost"), ("Act", "Tools and identity turn output into impact")]),
    S(98, "flow", "Day 2 Preview — From Attack to Assurance", evidence="ADMIN",
      steps=["Study attack mechanisms", "Separate case evidence", "Engineer hard controls", "Govern and operate"]),

    S(99, "section", "Day 2 — Attack, Defend, Govern, Operate", evidence="ADMIN", anchor="day2", accent="RED",
      note="Cases make the mechanisms concrete; controls then become testable evidence."),
    S(100, "flow", "Day 2 Dependency Map", evidence="SYN", sources=("S10", "S12", "S14"),
      steps=["Observe attack", "Trace authority", "Identify impact", "Place controls", "Prove and govern"]),
    S(101, "section", "Prompt Injection and Jailbreaks", evidence="ADMIN", anchor="prompt_injection", accent="RED",
      note="Distinguish changing application intent from bypassing model behaviour rules."),
    S(102, "compare", "Prompt Engineering vs Prompt Injection", evidence="DEF", sources=("S11",),
      left=["Prompt engineering", "Authorised user shapes the requested output", "Success serves the declared task"],
      right=["Prompt injection", "Untrusted text changes instructions or data flow", "Success serves an attacker or unintended objective"]),
    S(103, "cards", "Direct Prompt Injection", evidence="DEF", sources=("S11",),
      cards=[("Delivery", "Attacker writes into the user-facing prompt"), ("Conflict", "Text asks the model to ignore or reinterpret policy"), ("Control", "Detect attempts and constrain downstream authority")]),
    S(104, "cards", "Indirect Prompt Injection", evidence="DEF", sources=("S11", "S22"),
      cards=[("Delivery", "Payload sits in email, file, page or other content"), ("Trigger", "A legitimate user asks the system to process it"), ("Impact", "Model may treat data as instructions")]),
    S(105, "cards", "Cross-Modal Prompt Injection", evidence="DEF", sources=("S11",),
      cards=[("Carrier", "Image, audio or mixed-media content"), ("Recovery", "OCR, vision or transcription exposes instruction text"), ("Gap", "A text-only filter may never inspect the carrier")]),
    S(106, "flow", "Retrieval-Augmented Injection", evidence="DEF", sources=("S09", "S11"),
      steps=["Attacker writes source", "Indexer stores chunk", "Retriever selects chunk", "Model reads payload", "Output/action is altered"],
      note="Secure both who may write the corpus and what authority follows retrieval."),
    S(107, "cards", "Email and Document Injection", evidence="SIM", sources=("S11",),
      cards=[("Legitimate task", "Summarise a supplier email or invoice"), ("Hostile content", "Quoted text requests data or a changed instruction"), ("Boundary", "Reader remains tool-free; sensitive actions use independent verification")]),
    S(108, "flow", "Web and Browser Injection", evidence="DEF", sources=("S11", "S22"),
      steps=["Agent opens page", "Page supplies adversarial text", "Model interprets", "Browser/app action is proposed", "Policy blocks or confirms"],
      note="Browsing expands the untrusted context continuously."),
    S(109, "cards", "Context-File Injection", evidence="PROD", sources=("S18", "S19", "S31", "S44"),
      cards=[("Discovery", "Where configured, an agent discovers and loads project instruction files"), ("Risk", "A cloned repository may author instructions that influence tool use"), ("Control", "Inspect, scope and sandbox untrusted projects before tool use")],
      note="As of 20 Aug 2026; loading rules are product- and configuration-specific."),
    S(110, "flow", "Tool-Output Injection", evidence="DEF", sources=("S12",),
      steps=["Agent calls tool", "Tool returns attacker-controlled content", "Content enters context", "Planner changes course"],
      note="Tool output is data, not trusted policy."),
    S(111, "flow", "Memory-Based Instruction Persistence", evidence="DEF", sources=("S12",),
      steps=["Injection succeeds", "Summary or fact is saved", "Session ends", "Memory reloads", "Future behaviour changes"],
      note="Memory write policy and provenance are security controls."),
    S(112, "cards", "Jailbreak — Operational Definition", evidence="DEF", sources=("S11", "S13"),
      cards=[("Objective", "Bypass model or application behavioural restrictions"), ("Method", "Adversarial prompts, obfuscation or multi-turn pressure"), ("Distinction", "May not require changing a business task or calling a tool")]),
    S(113, "table", "Jailbreak vs Prompt Injection", evidence="DEF", sources=("S11", "S13"),
      headers=["Question", "Jailbreak", "Prompt injection"], rows=[["Target", "Safety/behaviour restriction", "Application instruction hierarchy"], ["Typical carrier", "User prompt", "User or external content"], ["Primary risk", "Disallowed output", "Changed task, disclosure or action"]]),
    S(114, "cards", "Common Jailbreak Families — Course Synthesis", evidence="SYN", sources=("S13",),
      cards=[("Framing", "Roleplay or fictional authority"), ("Obfuscation", "Encoding, spacing or substitution"), ("Composition", "Split intent across turns or modalities")]),
    S(115, "cards", "Why Model Guardrails Are Necessary but Insufficient", evidence="DEF", sources=("S09", "S11", "S22"),
      cards=[("Useful", "Block known patterns and create alert signals"), ("Fallible", "Novel phrasing and modalities can evade classifiers"), ("Hard boundary", "Policy, schema, least privilege and approval limit effects")]),
    S(116, "flow", "Case — EchoLeak: Verified Vulnerability, Not a Confirmed Breach", evidence="CASE-V", sources=("S25", "S40"),
      steps=["Attacker-controlled content", "Indirect prompt injection", "Copilot context/data access", "Exfiltration path", "Vendor remediation"],
      note="Aim/Microsoft sources accessed 20 Aug 2026; verified vulnerability, not confirmed exploitation or a breach."),
    S(117, "flow", "Published GitHub MCP Prompt-Injection Demonstration", evidence="CASE-R", sources=("S26",),
      steps=["Malicious repository content", "Coding agent reads issue/context", "MCP tools expose connected data", "Unintended action/exfiltration path"],
      note="Researcher demonstration; source accessed 20 Aug 2026. Production exploitation is not established."),
    S(118, "cards", "Simulation — Employee Data Entered into Public GenAI", evidence="SIM", sources=("S09", "S15"),
      cards=[("Action", "Employee pastes confidential data into an external service"), ("Risk", "Disclosure, retention and purpose may exceed policy"), ("Control", "Approved service, minimisation, DLP and user training")]),
    S(119, "flow", "Governance Case — Moffatt v Air Canada", evidence="CASE-V", sources=("S27",),
      steps=["Chatbot supplied incorrect information", "Customer relied on response", "Organisation disputed responsibility", "Tribunal held organisation responsible"],
      note="Tribunal decision 2024 BCCRT 149; accessed 20 Aug 2026. Reliability/accountability case, not prompt injection or cyberattack."),
    S(120, "table", "Incident, Demonstration, Evaluation, or Hypothetical?", evidence="SYN", sources=("S13",),
      headers=["Label", "Evidence threshold", "How to speak"], rows=[["Incident", "Observed production event", "State confirmed scope"], ["Demonstration", "Reproduced attack path", "State tested environment"], ["Evaluation", "Controlled model/system test", "Do not call it a breach"], ["Simulation", "Fictional teaching case", "Label every number synthetic"]]),
    S(121, "activity", "Activity 2 — Prompt-Injection Test", evidence="SIM", accent="RED",
      points=["Trace an indirect payload through a synthetic claims workflow", "Measure task success and attack success separately", "Select the earliest deterministic control that breaks the chain"]),
    S(122, "activity", "Activity 2 — Safe Harness and Test Boundaries", evidence="SIM",
      points=["Use only invented records", "Write to a local dummy log", "Block live email, shell, payment and production database tools"]),
    S(123, "activity", "Activity 2 — Establish a Clean Baseline", evidence="SIM",
      points=["Run legitimate tasks without hostile content", "Record expected output and permitted action", "Measure false blocks before adversarial changes"]),
    S(124, "activity", "Activity 2 — Test Controlled Variants", evidence="SIM",
      points=["Direct wording", "Indirect document or email wording", "Split and cross-modal variants"]),
    S(125, "activity", "Activity 2 — Add Hard Controls", evidence="SIM",
      points=["Restrict retrieval to the current case", "Validate recipients and tool parameters", "Require approval for sensitive disclosure or write action"]),
    S(126, "table", "Activity 2 — Read ASR and False Positives Together", evidence="SYN", sources=("S09", "S12"),
      headers=["Metric", "Definition", "Decision use"], rows=[["Attack success rate", "Successful attacks / attempts", "Residual adversarial exposure"], ["False-positive rate", "Blocked benign / benign tests", "Business cost of guardrail"], ["Clean-task success", "Correct benign / benign tests", "Utility under controls"]]),
    S(127, "break", "Morning Break", evidence="ADMIN", accent="AMBER"),

    S(128, "section", "Personal Data Across the AI Lifecycle", evidence="ADMIN", anchor="privacy_pdpa", accent="RED",
      note="Map personal data wherever the system collects, derives, stores, transmits or logs it."),
    S(129, "flow", "The GenAI Data Lifecycle", evidence="DEF", sources=("S09", "S15"),
      steps=["Collect", "Place in prompt/context", "Process in selected model environment", "Generate output", "Log/retain/delete"],
      note="Purpose and protection duties apply across the lifecycle, not only at initial collection."),
    S(130, "cards", "An Agent Can Add New Data Surfaces", evidence="DEF", sources=("S12", "S32"),
      cards=[("Observation", "Screenshots, browser state and external content"), ("Action", "Tool arguments, recipients and transaction details"), ("Persistence", "Memory, traces and scheduled-job state")]),
    S(131, "cards", "Tokens Are Authorities, Not Just Strings", evidence="DEF", sources=("S17", "S19"),
      cards=[("API key", "Authorises service use and spend"), ("OAuth token", "Carries user-approved scopes to an app"), ("Session credential", "Represents an authenticated browser or gateway session")]),
    S(132, "table", "Token-Leak Paths", evidence="DEF", sources=("S17", "S19", "S20"),
      headers=["Path", "Example", "Control"], rows=[["Context/log", "Secret pasted or returned by tool", "Redact and block"], ["Environment", "Process inherits broad variables", "Minimal environment"], ["Browser", "Cookie-bearing session", "Dedicated profile and logout"], ["Repository", "Credential file in workspace", "Secret scanning and isolation"]]),
    S(133, "flow", "Secret and Token Controls", evidence="DEF", sources=("S17", "S19"),
      steps=["Issue narrow scope", "Use short lifetime", "Isolate from context", "Monitor use", "Rotate or revoke"],
      note="Never give the model authority that the containing process does not need."),
    S(134, "table", "PDPA Obligations Relevant to AI", evidence="DEF", sources=("S15",),
      headers=["Obligation", "AI-system application"], rows=[["Notification / applicable basis", "Document the legal basis or exception and notify purposes as required; consent is not universal"], ["Purpose limitation", "Use data only for appropriate notified purposes"], ["Protection", "Secure prompts, outputs, memory, tools and logs"], ["Retention/transfer", "Delete when no longer needed and protect overseas transfers"], ["Accountability", "Assign responsibility and policies"]]),
    S(135, "flow", "Data-Breach Notification Decision", evidence="DEF", sources=("S15", "S16"),
      steps=["Contain and assess", "Significant harm likely?", "500 or more affected?", "Determine notifiability", "PDPC within 3 calendar days after determination"],
      note="Notify the PDPC if significant harm is likely OR the breach is of significant scale; notify affected individuals as soon as practicable where required."),
    S(136, "compare", "Purpose Limitation and Data Minimisation", evidence="DEF", sources=("S15",),
      left=["Over-collection", "Whole mailbox or drive", "Full identifiers in prompts", "Indefinite memory"],
      right=["Bounded design", "Task-specific folders/fields", "Tokenise or remove identifiers", "Purpose-linked retention"]),
    S(137, "cards", "Vendors, Subprocessors, and Overseas Transfers", evidence="DEF", sources=("S15",),
      cards=[("Data path", "Where prompts, files, outputs and logs travel"), ("Contract", "Use, retention, deletion, subprocessors and incident support"), ("Assurance", "Comparable protection for overseas transfers")]),
    S(138, "table", "Logs, Retention, and Deletion", evidence="SYN", sources=("S15",),
      headers=["Need", "Keep", "Limit"], rows=[["Security", "Identity, policy result, tool call and outcome", "Raw personal content where unnecessary"], ["Audit", "Decision and approval evidence", "Unlimited conversational history"], ["Operations", "Failure traces for defined period", "Orphaned memories after decommission"]]),
    S(139, "cards", "Privacy by Design for Agents", evidence="SYN", sources=("S14", "S15"),
      cards=[("Separate", "Dedicated identities, stores and runtime boundaries"), ("Minimise", "Only required fields enter model context"), ("Control", "Validate recipients and require review for sensitive disclosure")]),
    S(140, "flow", "Fictional Case — Singapore Claims Assistant Leak", evidence="SIM",
      steps=["Injected claim document", "Assistant retrieves unrelated records", "Tool prepares external transmission", "Egress/approval gap", "PDPA assessment"],
      note="All names, counts, systems and outcomes are fictional."),
    S(141, "flow", "Data-Leakage Mitigation Playbook", evidence="SYN", sources=("S15", "S16"),
      steps=["Detect", "Contain", "Revoke", "Preserve evidence", "Assess", "Notify", "Remediate"]),
    S(142, "content", "Evidence Exercise — Build the Agent Data Inventory", evidence="SIM",
      points=["List each field and whether it is personal data", "Name collection source, purpose, recipient and storage", "Set access, retention, deletion and breach owner"]),
    S(143, "break", "Lunch Break", evidence="ADMIN", accent="AMBER"),

    S(144, "section", "Frameworks Before Incident Analysis", evidence="ADMIN", anchor="frameworks", accent="TEAL",
      note="Use each framework for the question it was designed to answer."),
    S(145, "table", "The Framework Stack — Different Instruments", evidence="DEF", sources=("S10", "S11", "S12", "S13", "S14", "S15"),
      headers=["Instrument", "Primary question", "Use"], rows=[["NIST AI RMF", "How do we manage risk?", "Lifecycle"], ["OWASP", "What can go wrong?", "Risk / vulnerability taxonomy"], ["MITRE ATLAS", "How do adversaries operate?", "Techniques"], ["IMDA", "How do we bound and govern agents?", "Accountability"], ["PDPA", "What duties apply to personal data?", "Legal obligation"]]),
    S(146, "flow", "NIST AI RMF — Govern, Map, Measure, Manage", evidence="DEF", sources=("S10",),
      steps=["Govern", "Map", "Measure", "Manage"],
      note="The functions are iterative; governance is cross-cutting rather than a final sign-off."),
    S(147, "compare", "OWASP LLM and Agentic Top 10", evidence="DEF", sources=("S11", "S12"),
      left=["LLM application", "Prompt, data, model and output risks", "Useful for GenAI/RAG applications"],
      right=["Agentic application", "Goals, tools, identity, memory and coordination", "Useful when systems plan and act"]),
    S(148, "cards", "MITRE ATLAS", evidence="DEF", sources=("S13",),
      cards=[("Knowledge base", "Tactics and techniques against AI-enabled systems"), ("Coverage", "Maps tactics, techniques, mitigations and documented case studies"), ("Use", "Threat assessment, red teaming and detection design")]),
    S(149, "cards", "IMDA Agentic AI Governance Framework — Four Dimensions", evidence="DEF", sources=("S14",),
      cards=[("Assess and bound", "Choose suitable use cases; limit action space, data, tools and autonomy"), ("Human accountability", "Define significant checkpoints and meaningful approval"), ("Technical controls", "Apply controls and processes across the lifecycle"), ("End-user responsibility", "Enable informed use through transparency and training")],
      note="Action space and autonomy are distinct; some use cases may be unsuitable for agents."),
    S(150, "table", "PDPA and PDPC Guidance", evidence="DEF", sources=("S15", "S16"),
      headers=["Duty", "Security implication"], rows=[["Purpose/notification", "Document why data enters the system"], ["Protection", "Secure every prompt, memory, output and tool path"], ["Retention/transfer", "Control duration and overseas handling"], ["Breach notification", "Assess and notify when statutory tests are met"]],
      note="Use enacted PDPA obligations and published PDPC guidance. The 2 Jun 2026 GenAI document is a public-consultation proposal, not final guidance."),
    S(151, "table", "Positive Governance Case — Dayos Tiered IT Actions", evidence="CASE-V", sources=("S14",),
      headers=["Tier", "Documented pattern", "Control lesson"], rows=[["Tier 1", "Low severity and reversible; propose-confirm with requesting user; no human engineer", "Record reasoning/confidence; audit a cross-section biweekly"], ["Tier 2", "Agent diagnoses and proposes; human approval is required", "Place approval before the effect"], ["Tier 3", "High severity and limited reversibility", "Agent cannot perform the action"]],
      note="IMDA-contributed case study, not an independent security endorsement; accessed 20 Aug 2026."),
    S(152, "table", "OpenClaw Threat Walkthrough", evidence="PROD", sources=("S17",),
      headers=["Boundary", "Documented fact", "Security decision"], rows=[["Trust", "One trusted operator per gateway", "Separate mixed-trust users"], ["Tools", "High-impact control-plane/node tools exist", "Deny by default for untrusted content"], ["State", "Runtime directory contains sensitive material", "Protect host and file permissions"]],
      note="As of 20 Aug 2026; this is a configuration walkthrough, not a universal risk rating."),
    S(153, "table", "Hermes Threat Walkthrough", evidence="PROD", sources=("S18", "S19"),
      headers=["Boundary", "Documented fact", "Security decision"], rows=[["Execution", "Local and isolated backends are available", "Choose backend by risk"], ["Context", "Project files and skills can shape behaviour", "Scan and review"], ["Tools", "Approvals and filters provide layers", "Keep high-risk tools disabled unless needed"]],
      note="As of 20 Aug 2026; selected backend, approvals and tool configuration determine exposure."),

    S(154, "section", "When AI Can Act: Agentic Threats", evidence="ADMIN", anchor="agent_threats", accent="RED",
      note="Map each threat to a component, authority path and earliest control point."),
    S(155, "table", "OWASP Agentic Top 10 — System View", evidence="DEF", sources=("S12",),
      headers=["Component", "Representative risks"], rows=[["Goal/planner", "Goal hijack, rogue behaviour"], ["Tools/identity", "Tool misuse, privilege abuse, code execution"], ["State/comms", "Memory poisoning, insecure inter-agent communication"], ["System/human", "Supply chain, cascades, trust exploitation"]]),
    S(156, "flow", "ASI01 — Agent Goal Hijack", evidence="DEF", sources=("S12",),
      steps=["Hostile content", "Objective shifts", "Planner selects attacker-serving steps", "Tools execute"],
      note="Bind goals and validate actions independently of the model's stated rationale."),
    S(157, "cards", "ASI02 — Tool Misuse", evidence="DEF", sources=("S12",),
      cards=[("Legitimate tool", "Tool itself may work as designed"), ("Harmful use", "Parameters, sequence or context creates harm"), ("Control", "Allowlist, schema, policy and approval")]),
    S(158, "flow", "ASI03 — Identity and Privilege Abuse", evidence="DEF", sources=("S12",),
      steps=["Agent receives identity", "Scope exceeds task", "Compromised plan invokes privilege", "Action is attributed poorly"],
      note="Use a distinct agent identity with task-specific, short-lived permissions."),
    S(159, "cards", "ASI04 — Agentic Supply-Chain Vulnerabilities", evidence="DEF", sources=("S12",),
      cards=[("Components", "Models, skills, plugins, MCP, packages and prompts"), ("Change", "Runtime discovery and updates can alter reviewed behaviour"), ("Control", "Provenance, pinning, integrity, isolation and inventory")]),
    S(160, "table", "ASI05 — Unexpected Code Execution", evidence="DEF", sources=("S12",),
      headers=["Path", "Exposure", "Boundary"], rows=[["Generated code", "Unsafe program is proposed", "Review and test"], ["Interpreter/shell", "Code is executed", "Sandbox and allowlist"], ["Host escape", "Runtime boundary fails", "Hardened isolation and monitoring"]]),
    S(161, "flow", "ASI06 — Memory and Context Poisoning", evidence="DEF", sources=("S12",),
      steps=["Attacker supplies content", "Agent writes memory", "Provenance is lost", "Later session retrieves", "Behaviour persists"],
      note="Gate memory writes and retain source, author, timestamp and review status."),
    S(162, "cards", "ASI07 — Insecure Inter-Agent Communication", evidence="DEF", sources=("S12",),
      cards=[("Identity", "Can the receiver authenticate the sender?"), ("Message", "Is task intent and data integrity protected?"), ("Delegation", "Does authority narrow across handoffs?")]),
    S(163, "flow", "ASI08 — Cascading Failures", evidence="DEF", sources=("S12",),
      steps=["Wrong signal", "Automated acceptance", "Downstream transformation", "Repeated propagation", "System impact"],
      note="Validate at handoff boundaries and set fan-out, retry and budget limits."),
    S(164, "cards", "ASI09 — Human-Agent Trust Exploitation", evidence="DEF", sources=("S12", "S14"),
      cards=[("Presentation", "Confident explanation appears authoritative"), ("Human factor", "Time pressure and automation bias weaken review"), ("Control", "Show evidence and exact effect; audit approval quality")]),
    S(165, "compare", "ASI10 — Rogue Agents", evidence="DEF", sources=("S12",),
      left=["Supported statement", "OWASP identifies rogue-agent risk", "Evaluations may test concealment or misalignment"],
      right=["Unsupported leap", "An evaluation is a production breach", "A model finding proves every deployment behaves alike"]),
    S(166, "cards", "Malicious or Untrusted Skills", evidence="DEF", sources=("S12", "S18", "S19"),
      cards=[("Instructions", "A skill can steer tool selection and behaviour"), ("Code", "Bundled scripts can execute with host authority"), ("Control", "Review source, content, version, capabilities and updates")]),
    S(167, "flow", "CASE-R — ClawHavoc Reported Malicious-Skill Campaign", evidence="CASE-R", sources=("S37",),
      steps=["Public skill marketplace", "Skill content or setup lure", "User/agent installs", "Credential theft or malware path", "Researcher reports snapshot"],
      note="Koi, 1 Feb 2026; accessed 20 Aug 2026: 341 of 2,857 skills in its audited snapshot, including 335 linked to one campaign; not a current ecosystem rate or affected-user count."),
    S(168, "flow", "CASE-V — Amazon Q Developer Extension 1.84.0", evidence="CASE-V", sources=("S38",),
      steps=["Inappropriately scoped GitHub token", "Malicious code committed", "Release automatically included it", "Code distributed but syntax error prevented execution", "1.84.0 withdrawn; 1.85.0 released"],
      note="AWS bulletin published 23 Jul 2025, updated 25 Jul 2025; distribution is not proof of execution or customer compromise."),
    S(169, "flow", "CASE-V — Replit Agent and an Application Database", evidence="CASE-V", sources=("S39",),
      steps=["Agent had write authority", "Application database data was deleted", "Incident was detected", "Database was fully restored", "Default dev/prod separation was added"],
      note="Replit first-party post published 29 Jul 2025; it says no data was lost. Do not describe a permanent loss, customer breach or primary company database."),
    S(170, "table", "Network Exposure", evidence="DEF", sources=("S17", "S19"),
      headers=["Surface", "Question", "Control"], rows=[["Listener/gateway", "Who can reach it?", "Bind, authenticate, segment"], ["Messaging channel", "Who can trigger tools?", "Pair and allowlist"], ["Outbound web/API", "Where can data go?", "Proxy and destination allowlist"]]),
    S(171, "compare", "Egress, Code Execution, and Host Impact", evidence="DEF", sources=("S12", "S17", "S19"),
      left=["Compromise without hard boundaries", "Broad network", "User-level shell", "Long-lived credentials"],
      right=["Contained design", "Destination allowlist", "Non-root sandbox", "Short-lived scoped credentials"]),
    S(172, "flow", "Where Scheduling Is Enabled", evidence="DEF", sources=("S17", "S18", "S34"),
      steps=["Authorised user or scheduling tool creates task", "Task persists", "Credentials remain usable", "Future action executes"],
      note="Inventory schedules, require approval, cap lifetime and provide revocation."),
    S(173, "activity", "Activity 3 — Framework Stack", evidence="SIM", accent="VIOLET",
      points=["Use a fictional clinic assistant plus billing agent", "Match each decision question to a framework", "Avoid claiming that any one framework is complete"]),
    S(174, "activity", "Activity 3 — Threat and Metric Map", evidence="SIM",
      points=["Map an OWASP risk to an ATLAS technique only where direct evidence supports it; otherwise record no direct mapping", "Map controls to NIST/IMDA lifecycle evidence", "Attach PDPA duties where personal data is involved"]),
    S(175, "activity", "Activity 3 — Go-Live Gate", evidence="SIM",
      points=["Define clean-task and adversarial tests", "Name the accountable risk owner", "Set conditions for go, conditional go or no-go"]),
    S(176, "activity", "Activity 4 — Case Review", evidence="SYN", sources=("S25", "S40", "S38", "S39", "S37"), accent="AMBER",
      points=["EchoLeak: CASE-V verified vulnerability, not confirmed breach", "Amazon Q extension and Replit database event: CASE-V first-party accounts", "ClawHavoc: CASE-R research snapshot with denominator and limitations"]),
    S(177, "activity", "Activity 4 — Kill Chain and Supply Gate", evidence="SIM",
      points=["Reconstruct delivery through impact", "Find the earliest effective break point", "Apply provenance, integrity, capability, isolation, approval and operations gates"]),
    S(178, "break", "Afternoon Break", evidence="ADMIN", accent="AMBER"),

    S(179, "section", "From Threats to an Operating Control System", evidence="ADMIN", anchor="controls", accent="TEAL",
      note="Controls must prevent, detect, respond and leave evidence."),
    S(180, "cards", "Defence in Depth for GenAI and Agents", evidence="SYN", sources=("S10", "S12", "S14"),
      cards=[("Prevent", "Bound inputs, identities, tools and runtime"), ("Detect", "Observe sequences, policy results and anomalies"), ("Respond", "Stop, revoke, preserve, recover"), ("Govern", "Own risk, test change and review evidence")]),
    S(181, "flow", "Step 1 — Inventory and Risk-Tier the Use Case", evidence="SYN", sources=("S10", "S14"),
      steps=["Name owner", "State purpose", "List data/components", "Classify impact", "Assign tier"]),
    S(182, "cards", "Step 2 — Bound Data, Tools, and Autonomy", evidence="DEF", sources=("S14",),
      cards=[("Data", "Allowed sources, fields and retention"), ("Tools", "Allowed operations and parameter ranges"), ("Autonomy", "Stop conditions, budgets and approval points")]),
    S(183, "flow", "Step 3 — Give Every Agent a Scoped Identity", evidence="DEF", sources=("S12", "S14"),
      steps=["Create distinct identity", "Grant minimum scope", "Use short lifetime", "Log use", "Revoke on stop/change"]),
    S(184, "flow", "Step 4 — Guardrails and Schema Validation", evidence="SYN", sources=("S09", "S11"),
      steps=["Screen input", "Generate/plan", "Validate structured parameters", "Apply policy", "Screen output"],
      note="Model-based filters add friction; deterministic checks bound actions."),
    S(185, "cards", "Step 5 — Sandbox Code and Files", evidence="SYN", sources=("S17", "S19", "S20", "S21"),
      cards=[("Process", "For containerised workloads, prefer non-root and no-new-privileges where supported"), ("Filesystem", "Workspace-only or read-only mounts"), ("Resources", "CPU, memory, time and process limits")]),
    S(186, "flow", "Step 6 — Control Network Egress", evidence="SYN", sources=("S12", "S30"),
      steps=["Default deny", "Allow named destinations", "Bind destination secrets", "Inspect payload", "Alert exceptions"]),
    S(187, "flow", "Step 7 — Deterministic Human Approval", evidence="DEF", sources=("S14",),
      steps=["Policy detects risk", "Prepare exact action", "Show effect and evidence", "Approve once or reject", "Execute or stop"]),
    S(188, "compare", "Make Human Approval Meaningful", evidence="DEF", sources=("S14",),
      left=["Weak approval", "Vague ‘continue?’", "Standing permission", "No outcome review"],
      right=["Meaningful approval", "Exact recipient/data/value", "One action with expiry", "Rejection and override audited"]),
    S(189, "table", "Step 8 — Log the Decision and the Action", evidence="SYN", sources=("S10", "S14"),
      headers=["Evidence", "Why keep it"], rows=[["Trace and identity", "Attribute one end-to-end run"], ["Inputs/source provenance", "Explain what influenced the model"], ["Policy and approval", "Prove control outcome"], ["Tool arguments/result", "Reconstruct actual effect"]]),
    S(190, "cards", "Step 9 — Monitor Sequences, Not Only Events", evidence="SYN", sources=("S12", "S13"),
      cards=[("Sequence", "Unexpected tool order or fan-out"), ("Boundary", "Repeated denials, scope errors or new destinations"), ("Consumption", "Runaway turns, time, tokens or spend")]),
    S(191, "table", "Step 10 — Red-Team Before Go-Live", evidence="DEF", sources=("S09", "S12", "S14"),
      headers=["Test family", "Evidence"], rows=[["Clean tasks", "Utility and false blocks"], ["Injection/jailbreak", "Attack success by family"], ["Tools/identity", "Unsafe or denied action attempts"], ["Memory/supply chain", "Persistence and provenance controls"], ["Recovery", "Kill switch, revoke and restore"]]),
    S(192, "cards", "A Measurable Go-Live Gate", evidence="SYN", sources=("S10", "S14"),
      cards=[("Performance", "Task success on representative clean cases"), ("Security", "Attack and unsafe-action results by threat family"), ("Operations", "Approval quality, detection and recovery tests")],
      note="Thresholds are organisation-defined; do not invent universal percentages."),
    S(193, "table", "Incident Response for an AI Agent", evidence="SYN", sources=("S13", "S16"),
      headers=["Phase", "Immediate action", "Evidence or decision"],
      rows=[["Identify", "Stop work and isolate the runtime", "Affected goal, session, tools and data"],
            ["Contain", "Revoke credentials and block egress", "Identity, scopes, destinations and timestamps"],
            ["Assess", "Preserve logs and determine impact", "Personal data, actions, reversibility and notification test"],
            ["Recover", "Restore clean state and re-test controls", "Root cause, corrective action, owner and approval"]]),
    S(194, "flow", "Safe Change, Rollback, and Decommissioning", evidence="SYN", sources=("S10", "S14", "S15"),
      steps=["Inventory change", "Re-test", "Stage rollout", "Rollback if gate fails", "Revoke/delete/archive at retirement"]),
    S(195, "table", "Shared Responsibility Across the Agent Lifecycle", evidence="SYN", sources=("S14", "S15"),
      headers=["Role", "Evidence owned"], rows=[["Provider", "Limits, safety data, terms and change notice"], ["Builder", "Architecture, tools, provenance and tests"], ["Deployer", "Purpose, access, autonomy and approval"], ["Operator", "Monitoring, incident response and re-test"], ["User/approver", "Verification and escalation"]]),
    S(196, "table", "Responsible AI Principles Become Controls", evidence="SYN", sources=("S09", "S14", "S15"),
      headers=["Principle", "Observable control"], rows=[["Accountability", "Named owner and residual-risk sign-off"], ["Transparency", "Capability, data and appeal notice"], ["Fairness", "Segment testing and remediation"], ["Privacy", "Minimisation, purpose and retention"], ["Human agency", "Meaningful review and remedy"]]),
    S(197, "activity", "Activity 5 — Governance Deployment Gate", evidence="SIM", accent="TEAL",
      points=["Review a fictional bank collections agent", "Use only synthetic segment and test data", "Decide go, conditional go or no-go"]),
    S(198, "activity", "Activity 5 — Bias, Privacy, and Autonomy Evidence", evidence="SIM",
      points=["Compare performance by affected group", "Map personal-data purpose and disclosure", "Set read, recommend, prepare and execute boundaries"]),
    S(199, "activity", "Activity 5 — Go, Conditional Go, or No-Go", evidence="SIM",
      points=["State evidence and uncertainty", "Name conditions, accountable owner and review date", "Define kill switch, rollback and escalation"]),
    S(200, "table", "Production Security Checklist", evidence="SYN", sources=("S10", "S12", "S14", "S15"),
      headers=["Gate", "Minimum evidence"], rows=[["Own", "Purpose, tier and accountable roles"], ["Bound", "Data, identity, tools, network and autonomy"], ["Assure", "Clean/adversarial tests and approval quality"], ["Operate", "Logs, alerts, response and rollback"], ["Sustain", "Change control and decommissioning"]]),
    S(201, "flow", "Course Synthesis — Bound the Authority", evidence="SYN", sources=("S09", "S12", "S14"),
      steps=["Know the operating layers", "Assume content can be hostile", "Limit identity and tools", "Gate irreversible effects", "Preserve evidence"]),
    S(202, "cards", "Day 2 Recap — From Attack to Assurance", evidence="SYN", sources=("S10", "S12", "S14", "S15"),
      cards=[("Attack", "Trace content through authority to effect"), ("Defend", "Use layered, deterministic boundaries"), ("Govern", "Measure, own and improve residual risk")]),

    S(203, "content", "Assessment Reminder", evidence="ADMIN",
      points=["Complete required digital attendance", "Use slides, Learner Guide and activity evidence", "Submit the required assessment files on the LMS"]),
    S(204, "flow", "Assessment Flow", evidence="ADMIN",
      steps=["TRAQOM", "Assessment attendance", "WA then case study", "Submit on LMS", "Sign summary record"]),
    S(205, "attendance", "Digital Attendance — Mandatory", evidence="ADMIN",
      points=["Scan the LMS QR code", "Confirm assessment attendance", "Ask the trainer to verify any error"]),
    S(206, "lms", "Courseware and Assessment on the LMS", evidence="ADMIN",
      points=["Download the current learner-facing materials", "Upload only requested assessment evidence", "Do not upload answer keys or production secrets"]),
    S(207, "thankyou", "Thank You — Bound the Authority, Preserve the Evidence", evidence="ADMIN",
      points=["Assume compromise is possible", "Keep effects bounded and attributable", "Improve from measured evidence"]),
]


NON_TEACHING_KINDS = {"cover", "section", "break", "attendance", "trainer", "lms", "thankyou"}

assert len(SLIDES) == 207, f"Expected 207 slides, found {len(SLIDES)}"
assert [s["n"] for s in SLIDES] == list(range(1, 208)), "Slide numbers must be 1..207"
assert all(src in SOURCES for slide in SLIDES for src in slide["sources"]), "Unknown source ID"

for slide in SLIDES:
    if slide["kind"] in NON_TEACHING_KINDS:
        continue
    payload = (slide.get("points") or slide.get("cards") or slide.get("rows") or
               slide.get("steps") or slide.get("left"))
    assert payload and len(payload) >= 3, f"Thin teaching slide {slide['n']}: {slide['title']}"
