#!/usr/bin/env python3
"""Machine-readable v4.x slide content — 1-day course architecture.

The course was rebuilt on 25 Aug 2026 from a 2-day security course into a
1-Day (8h) course with three topics mapped one-to-one onto LO1/LO2/LO3:

  Topic 1 (LO1)  Generative AI, Agentic AI and AI Agents            (9:30-11:30)
  Topic 2 (LO2)  Prompt Engineering and Post-Training               (12:30-14:30, lunch 12:30-13:30)
  Topic 3 (LO3)  Security Risk of Autonomous AI Agents              (14:30-17:00)
  Assessment                                                        (17:00-18:00)

Evidence policy for v4 is "lighter touch": real factual claims and named cases
carry an evidence label + source ID; concept/definition slides may stand on their
own.  Detailed procedures live in the Learner Guide and activity packs.
"""

VERSION = "4.2"
VERSION_DATE = "25 August 2026"
COURSE_CODE = "TGS-2025060473"
TITLE = "AI Security for Autonomous AI Agents"

SOURCES = {
    # --- History / concepts
    "S05": {"title": "Vaswani et al., Attention Is All You Need (2017)", "url": "https://arxiv.org/abs/1706.03762"},
    "S06": {"title": "Brown et al., Language Models are Few-Shot Learners (GPT-3)", "url": "https://arxiv.org/abs/2005.14165"},
    "S07": {"title": "Ouyang et al., Training language models to follow instructions (InstructGPT)", "url": "https://arxiv.org/abs/2203.02155"},
    "S08": {"title": "OpenAI — Introducing ChatGPT (30 Nov 2022)", "url": "https://openai.com/index/chatgpt/"},
    # --- Context & harness engineering
    "S10": {"title": "Anthropic — Effective context engineering for AI agents (Sep 2025)", "url": "https://www.anthropic.com/engineering/effective-context-engineering-for-ai-agents"},
    "S11": {"title": "Karpathy on 'context engineering' (X, 25 Jun 2025)", "url": "https://x.com/karpathy/status/1937902205765607626"},
    "S12": {"title": "Anthropic — How Claude Code works (agentic harness)", "url": "https://code.claude.com/docs/en/how-claude-code-works"},
    "S13": {"title": "OpenAI — Harness engineering: Codex in an agent-first world", "url": "https://openai.com/index/harness-engineering/"},
    "S14": {"title": "Anthropic — How we built our multi-agent research system (13 Jun 2025)", "url": "https://www.anthropic.com/engineering/built-multi-agent-research-system"},
    "S15": {"title": "Anthropic — Agent Skills / Claude Code", "url": "https://code.claude.com/docs/en/skills"},
    "S16": {"title": "Model Context Protocol (MCP) documentation", "url": "https://modelcontextprotocol.io/docs/getting-started/intro"},
    # --- Use cases
    "S20": {"title": "PetaPixel — Mango launches photorealistic AI-generated campaign (Jul 2024)", "url": "https://petapixel.com/2024/07/16/fashion-brand-mango-launches-photorealistic-ai-generated-campaign/"},
    "S21": {"title": "CNN — H&M to create AI 'digital twins' of models (Mar 2025)", "url": "https://www.cnn.com/2025/03/28/style/h-and-m-ai-models-intl-scli"},
    "S22": {"title": "CNN — AI models in Guess ad in Vogue's August 2025 issue", "url": "https://www.cnn.com/2025/07/31/style/vogue-ai-models-guess-campaign"},
    "S24": {"title": "Forbes — Coca-Cola AI-generated Christmas ad, again (Nov 2025)", "url": "https://www.forbes.com/sites/danidiplacido/2025/11/04/coca-cola-sparks-backlash-with-ai-generated-christmas-ad-again/"},
    "S25": {"title": "Klarna — AI assistant handles two-thirds of chats in first month (27 Feb 2024)", "url": "https://www.klarna.com/international/press/klarna-ai-assistant-handles-two-thirds-of-customer-service-chats-in-its-first-month/"},
    "S26": {"title": "Forbes — Klarna reverses on AI, re-hires human agents (May 2025)", "url": "https://www.forbes.com/sites/quickerbettertech/2025/05/18/business-tech-news-klarna-reverses-on-ai-says-customers-like-talking-to-people/"},
    # --- Products / agents
    "S30": {"title": "OpenClaw — Wikipedia (naming and adoption history)", "url": "https://en.wikipedia.org/wiki/OpenClaw"},
    "S31": {"title": "OpenClaw — official site and docs", "url": "https://docs.openclaw.ai/"},
    "S32": {"title": "Peter Steinberger — GitHub (steipete)", "url": "https://github.com/steipete"},
    "S33": {"title": "Hermes Agent (Nous Research) — documentation", "url": "https://hermes-agent.nousresearch.com/docs/"},
    "S34": {"title": "Hermes Agent — Desktop app user guide", "url": "https://hermes-agent.nousresearch.com/docs/user-guide/desktop"},
    "S35": {"title": "Hermes Agent — Security", "url": "https://hermes-agent.nousresearch.com/docs/user-guide/security"},
    "S36": {"title": "MiniMax — MiniMax-M2 news and platform", "url": "https://www.minimax.io/news/minimax-m2"},
    "S37": {"title": "MiniMax — platform docs (API and models)", "url": "https://platform.minimax.io/docs/guides/text-generation"},
    # --- Governance / risk
    "S40": {"title": "IMDA Model AI Governance Framework for Generative AI", "url": "https://aiverifyfoundation.sg/resources/mgf-gen-ai/"},
    "S41": {"title": "PDPC Advisory Guidelines on Key Concepts in the PDPA", "url": "https://www.pdpc.gov.sg/guidelines-and-consultation/2020/03/advisory-guidelines-on-key-concepts-in-the-personal-data-protection-act"},
    "S42": {"title": "PDPC Guide on Managing and Notifying Data Breaches under the PDPA", "url": "https://www.pdpc.gov.sg/help-and-resources/2021/05/guide-on-managing-and-notifying-data-breaches-under-the-pdpa"},
    "S43": {"title": "OWASP Top 10 for LLM Applications", "url": "https://genai.owasp.org/llm-top-10/"},
    "S44": {"title": "OWASP Top 10 for Agentic Applications (2026)", "url": "https://genai.owasp.org/resource/owasp-top-10-for-agentic-applications-for-2026/"},
    "S45": {"title": "NIST AI Risk Management Framework", "url": "https://www.nist.gov/itl/ai-risk-management-framework"},
    "S46": {"title": "Moffatt v Air Canada, 2024 BCCRT 149", "url": "https://www.canlii.org/en/bc/bccrt/doc/2024/2024bccrt149/2024bccrt149.html"},
    "S47": {"title": "Replit — securing vibe coding after an agent deleted a database (Jul 2025)", "url": "https://replit.com/blog/doubling-down-on-our-commitment-to-secure-vibe-coding"},
    "S48": {"title": "WEF — Future of Jobs Report 2025", "url": "https://www.weforum.org/press/2025/01/future-of-jobs-report-2025-78-million-new-job-opportunities-by-2030-but-urgent-upskilling-needed-to-prepare-workforces/"},
    "S49": {"title": "Anthropic — the Anthropic Economic Index", "url": "https://www.anthropic.com/news/the-anthropic-economic-index"},
    "S50": {"title": "Anthropic — Claude Code sandboxing", "url": "https://www.anthropic.com/engineering/claude-code-sandboxing"},
    "S52": {"title": "Peter Steinberger — official 2026 speaker photograph", "url": "https://github.com/steipete/speaking/blob/master/Pictures/ai-engineer-worlds-fair-2026.jpg"},
    "S53": {"title": "Anthropic — Claude Code (repository)", "url": "https://github.com/anthropics/claude-code"},
    "S54": {"title": "OpenAI — Codex (repository)", "url": "https://github.com/openai/codex"},
    "S55": {"title": "DeepSeek Harness (dsh) — developer preview repository", "url": "https://github.com/deepseek-ai/deepseek-harness"},
    "S56": {"title": "OpenClaw — repository", "url": "https://github.com/openclaw/openclaw"},
    "S57": {"title": "Hermes Agent (Nous Research) — repository", "url": "https://github.com/NousResearch/hermes-agent"},
    "S58": {"title": "Prime Agent (Prime Intellect) — repository", "url": "https://github.com/PrimeIntellect-ai/prime-agent"},
    "S59": {"title": "OpenWorker — open standard for employing AI in organisations", "url": "https://github.com/openworker-io/openworker"},
    "S60": {"title": "QM (Quartermaster, Y Combinator) — multiplayer agent harness", "url": "https://github.com/yc-software/qm"},
}


def S(n, kind, title, *, evidence="SYN", sources=(), kicker=None, accent="BLUE",
      points=None, cards=None, headers=None, rows=None, left=None, right=None,
      steps=None, note=None, anchor=None, image=None, lhead=None, rhead=None,
      cols=None, widths=None, img_w=None, size=None, fsize=None, video_url=None,
      video_embed=None):
    """Return one normalized slide dictionary."""
    d = {
        "n": n, "kind": kind, "title": title, "evidence": evidence,
        "sources": list(sources), "source_urls": [SOURCES[x]["url"] for x in sources],
        "accent": accent,
    }
    for key, value in (("kicker", kicker), ("points", points), ("cards", cards),
                       ("headers", headers), ("rows", rows), ("left", left),
                       ("right", right), ("steps", steps), ("note", note),
                       ("anchor", anchor), ("image", image), ("lhead", lhead),
                       ("rhead", rhead), ("cols", cols), ("widths", widths),
                       ("img_w", img_w), ("size", size), ("fsize", fsize),
                       ("video_url", video_url), ("video_embed", video_embed)):
        if value is not None:
            d[key] = value
    return d


SLIDES = [
    # ============================================================ ADMIN (front)
    S(1, "cover", TITLE, evidence="ADMIN", kicker=COURSE_CODE,
      points=["Tertiary Infotech Pte Ltd", "One day · 8 hours", "Version 4.1"]),
    S(2, "attendance", "Digital Attendance — TRAQOM", evidence="ADMIN",
      points=["Scan the LMS QR code", "Complete attendance before class begins",
              "Ask the trainer if your confirmation is not shown"]),
    S(3, "trainer", "About the Trainer — General", evidence="ADMIN",
      points=["Name and designation", "Qualifications and industry expertise",
              "Training experience and contact"]),
    S(4, "trainer", "About the Trainer — Dr Alfred Ang", evidence="ADMIN",
      points=["AI and digital-transformation educator",
              "Applied generative-AI and AI-agent experience", "Tertiary Infotech Pte Ltd"]),
    S(5, "cards", "Who Is in the Room?", evidence="ADMIN",
      cards=[("Role", "What service or team do you work in?"),
             ("AI today", "Where do you already meet AI at work?"),
             ("Goal", "What do you want to be able to do by 6pm?")]),
    S(6, "cards", "Ground Rules for a Hands-On Day", evidence="ADMIN",
      cards=[("Use the demos", "Every activity is a ready-made website or chatbot — no coding"),
             ("Fictional data only", "Never paste real personal or company data into a demo"),
             ("Ask and share", "Try prompts, compare answers, and reflect together")]),
    S(7, "cards", "Learning Outcomes", evidence="ADMIN",
      cards=[("LO1", "Demonstrate generative AI concepts and applications"),
             ("LO2", "Apply prompt engineering and analyse output variations"),
             ("LO3", "Identify ethical risks and analyse bias in AI content")]),
    S(8, "flow", "One-Day Learning Journey", evidence="ADMIN",
      steps=["Topic 1 — GenAI, Agentic AI & Agents", "Topic 2 — Prompt Engineering",
             "Topic 3 — Security & Governance", "Assessment"],
      note="Three topics map one-to-one onto LO1, LO2 and LO3; the assessment closes the day."),
    S(9, "table", "How the Day Is Assessed", evidence="ADMIN",
      headers=["Instrument", "Covers", "What you do"],
      rows=[["Written Assessment (SAQ)", "K1–K5", "Five short written answers, one per knowledge statement"],
            ["Practical Performance", "LO1–LO3 (A1–A5)", "Three reflection tasks on the activities you completed today"],
            ["Format", "—", "Open book · Competent / Not Yet Competent"]],
      widths=[0.28, 0.16, 0.56]),
    S(10, "flow", "Briefing for Assessment", evidence="ADMIN",
      steps=["Read each task", "Draw on today's activities", "Write from your own evidence",
             "Justify your reasoning", "Submit on the LMS"],
      note="The briefing for assessment is delivered before the assessment begins."),
    S(11, "lms", "Courseware and Activities on the LMS", evidence="ADMIN",
      points=["Download the current learner-facing files from the LMS",
              "Open each activity website directly in your browser — nothing to install",
              "Keep every test synthetic, local and reversible"]),

    # ============================================================ TOPIC 1
    S(12, "section", "Generative AI, Agentic AI and AI Agents", evidence="ADMIN",
      anchor="topic1", accent="VIOLET", kicker="TOPIC 1 · LO1",
      note="From a chat box to systems that plan and act — history, mechanics, use cases and agents."),
    S(13, "flow", "What Topic 1 Will Answer", evidence="SYN",
      steps=["How did we get here?", "How does GenAI actually work?", "What is context engineering?",
             "What is an agentic loop?", "What is an AI agent?"],
      note="Each question builds the vocabulary you need for prompt engineering and security later."),

    # ---- Brief history
    S(14, "flow", "A Very Short History of AI, 2023–2026", evidence="HIST", accent="VIOLET",
      steps=["2023 · Generative AI", "2024 · Context Engineering",
             "2025 · Harness Engineering", "2026 · AI Agents"],
      note="Each year did not replace the last — it added a new layer on top of it."),
    S(15, "cards", "The Four Waves in Plain Words", evidence="SYN", accent="VIOLET",
      cards=[("2023 — Generative AI", "ChatGPT makes text and image generation mainstream"),
             ("2024 — Context Engineering", "We learn to feed models the right information, not just a prompt"),
             ("2025 — Harness Engineering", "We wrap models in loops that plan, act and verify — agentic AI"),
             ("2026 — AI Agents", "Deployed agents act across our apps, chats and tools")], cols=4),
    S(16, "content", "2023 — Generative AI Goes Mainstream", evidence="HIST", sources=("S08",), accent="VIOLET",
      points=["ChatGPT launched on 30 November 2022 and reached mass adoption through 2023",
              "One natural-language box exposed writing, coding, translation and analysis to everyone",
              "Businesses began asking not 'can it chat?' but 'what work can it do?'"]),
    S(17, "image", "2024 — Context Engineering", evidence="HIST", sources=("S10", "S11"), accent="VIOLET",
      image="visual-context-engineering-v41.png", img_w=6.45,
      points=[("Beyond the prompt", "The model also needs the right supporting information"),
              ("The context window", "Instructions, history, memory, tools and retrieved data meet here"),
              ("The craft", "Select just the right tokens for the model's next step")]),
    S(18, "image", "2025 — Harness Engineering and Agentic AI", evidence="HIST", sources=("S12", "S13"), accent="VIOLET",
      image="visual-harness-engineering-v41.png", img_w=6.45,
      points=[("Loop", "Gather context, plan, act and verify until the goal is met"),
              ("Tools", "The harness gives the model controlled ways to affect real systems"),
              ("Safety", "Permissions, sandboxes and verification constrain each action")]),
    S(19, "content", "2026 — The Year of AI Agents", evidence="HIST", sources=("S30", "S33"), accent="VIOLET",
      points=["Personal and organisational agents such as OpenClaw and Hermes reached everyday users",
              "Agents now live inside WhatsApp, Telegram, email and business apps",
              "The question shifted again: how do we let agents act safely on our behalf?"]),

    # ---- How GenAI works
    S(20, "section", "How Generative AI Works", evidence="ADMIN", accent="VIOLET",
      kicker="TOPIC 1", note="Training, inference, and the autoregressive language model."),
    S(21, "cards", "What 'Generative' Means", evidence="DEF", accent="VIOLET",
      cards=[("Generative AI", "Produces new text, image, audio, video or code from patterns it has learned"),
             ("Discriminative AI", "Sorts or scores existing input — spam / not-spam, fraud / not-fraud"),
             ("Why it matters", "Service teams use both: generate a reply, and classify a request")]),
    S(22, "flow", "Two Phases: Training and Inference", evidence="DEF", sources=("S06",), accent="VIOLET",
      steps=["Gather large text corpora", "Train — adjust billions of parameters", "Ship the model",
             "Inference — you prompt, it responds"],
      note="Training happens once and is expensive; inference happens every time you use the model."),
    S(23, "flow", "How an Autoregressive LLM Writes", evidence="DEF", sources=("S05",), accent="VIOLET",
      steps=["Read your context as tokens", "Predict the next token's probabilities",
             "Pick one token", "Append it and repeat"],
      note="A large language model writes one token at a time, each based on everything before it."),
    S(24, "cards", "Why the Same Prompt Can Differ", evidence="DEF", accent="VIOLET",
      cards=[("Probabilities", "The model samples from likely next tokens, not a fixed lookup"),
             ("Temperature", "Higher settings add variety; lower settings add consistency"),
             ("Context", "Change the surrounding information and the whole answer shifts")]),
    S(25, "cards", "Strengths and Limits for Service Work", evidence="DEF", accent="VIOLET",
      cards=[("Strong at", "Drafting, summarising, translating, reformatting, brainstorming"),
             ("Weak at", "Facts it was never given — it can sound confident yet be wrong"),
             ("Rule", "Treat fluent output as a draft to verify, not as truth")]),

    # ---- Use cases (real, verified)
    S(26, "section", "Generative AI in the Real World", evidence="ADMIN", accent="TEAL",
      kicker="TOPIC 1", note="Real, dated examples — how generation is already changing work."),
    S(27, "fashion_case", "Fashion Models Are Now Generated", evidence="CASE-V", sources=("S20", "S21", "S22"), accent="TEAL",
      image="fashion-model-synthetic-v41.png",
      cards=[("Mango, Jul 2024", "Ran its first fully AI-generated campaign for its teen 'Sunset Dream' line across 95 markets"),
             ("H&M, 2025", "Announced AI 'digital twins' of 30 real models; first labelled images appeared mid-2025"),
             ("Guess, Aug 2025", "A Guess ad using AI-generated models ran in Vogue's August issue and drew wide debate")]),
    S(28, "video", "AI-Generated Video Is Overtaking Whole Industries", evidence="SYN", accent="TEAL",
      image="yt-qNBngP40P_s.jpg",
      video_url="https://www.youtube.com/shorts/qNBngP40P_s",
      video_embed="https://www.youtube.com/embed/qNBngP40P_s",
      points=[("AI-generated", "This short vertical video was made with generative AI — no camera, cast or crew"),
              ("Marketing & advertising", "Brands now generate campaign video in hours, not weeks"),
              ("Movies", "AI is moving into film production — visuals, scenes and effects"),
              ("Music", "AI-generated tracks and videos are reshaping the music industry too")],
      note="Play the Short in-slide, or tap 'Watch the Short'. Discuss: could your team use this — and what could go wrong?"),
    S(29, "flow", "Customer Service: The Klarna Story", evidence="CASE-V", sources=("S25", "S26"), accent="TEAL",
      steps=["Feb 2024 — AI assistant handles 2/3 of chats", "Work of ~700 agents in month one",
             "Resolution time 11 min to under 2 min", "May 2025 — re-hires humans for quality"],
      note="A real cautionary tale: automate the routine, but keep humans for judgement and empathy."),
    S(30, "cards", "Where Service Teams Apply GenAI Today", evidence="SYN", accent="TEAL",
      cards=[("Front desk", "Draft replies, translate, summarise long threads"),
             ("Back office", "Turn notes into reports; extract data from documents"),
             ("Marketing", "Generate copy, images and short video for campaigns")]),

    # ---- Context engineering
    S(31, "section", "Context Engineering", evidence="ADMIN", accent="BLUE",
      kicker="TOPIC 1", note="The model is only as good as the context you give it."),
    S(32, "cards", "Prompt Engineering vs Context Engineering", evidence="DEF", sources=("S10", "S11"),
      cards=[("Prompt engineering", "Wording one instruction well"),
             ("Context engineering", "Assembling everything the model sees before it answers"),
             ("The shift", "Real applications manage context, not just a clever prompt")]),
    S(33, "cards", "The Six Ingredients of Context", evidence="DEF", sources=("S10",),
      cards=[("System prompt", "Who the AI is and its rules"),
             ("User prompt", "The task you asked for right now"),
             ("History", "Earlier turns in this conversation"),
             ("Memory", "Facts kept across sessions"),
             ("Tools", "Functions it can call to act or fetch data"),
             ("Retrieved data", "Documents pulled in for this task")], cols=3),
    S(34, "flow", "How an Agent Gathers Context for a Task", evidence="SYN", sources=("S10",),
      steps=["You give a goal", "It reads its system prompt and memory",
             "It retrieves relevant files or data", "It calls tools for fresh facts",
             "It assembles all of this, then answers"],
      note="Example: 'Reply to this guest email' → it pulls the booking, the policy doc and past replies first."),
    S(35, "cards", "A Worked Context Example", evidence="SYN",
      cards=[("Task", "'Draft a refund reply to Mr Tan'"),
             ("Context gathered", "Booking record + refund policy + tone guide + the original email"),
             ("Result", "A grounded reply, not a generic guess")]),

    # ---- Agentic loop & harness engineering  (visual pipeline requested)
    S(36, "section", "The Agentic Loop and Harness Engineering", evidence="ADMIN", accent="BLUE",
      kicker="TOPIC 1", note="What turns a model that answers into a system that acts."),
    S(37, "flow", "The Agentic Loop — A Visual Pipeline", evidence="DEF", sources=("S12",), accent="BLUE",
      steps=["Context — gather goal & information", "Plan — decide the next step",
             "Execute — call a tool / take an action", "Verify — check the result"],
      note="The loop repeats until the goal is met. Anthropic's harness uses gather → act → verify; 'plan' is shown here as a teaching step."),
    S(38, "cards", "What a Harness Adds Around the Model", evidence="DEF", sources=("S12", "S13"), accent="BLUE",
      cards=[("The loop", "Runs context → plan → execute → verify repeatedly"),
             ("Tool access", "Lets the model read files, run commands, call APIs"),
             ("State & safety", "Tracks progress and enforces permissions and sandboxes")]),
    S(39, "cards", "Two Harnesses You May Have Heard Of", evidence="PROD", sources=("S12", "S13"), accent="BLUE",
      cards=[("Claude Code", "Anthropic's coding agent — the 'agentic harness around Claude'"),
             ("Codex", "OpenAI's coding agent; OpenAI calls the discipline 'harness engineering'"),
             ("Same idea", "A loop + tools + a sandbox around a general model")]),
    S(40, "table", "The Coding Harnesses — Claude Code, Codex, DeepSeek", evidence="PROD",
      sources=("S53", "S54", "S55"), accent="BLUE",
      headers=["Harness", "What it is", "Where to find it"],
      rows=[["Claude Code", "Anthropic's terminal coding agent — reads your codebase, edits files, runs tests and git by natural language", "github.com/anthropics/claude-code"],
            ["Codex", "OpenAI's coding agent; its execution engine (the 'harness') was open-sourced in Aug 2026", "github.com/openai/codex"],
            ["DeepSeek Harness (dsh)", "DeepSeek's plugin-based, model-agnostic harness — a v0.1 developer preview", "github.com/deepseek-ai/deepseek-harness"]],
      widths=[0.22, 0.5, 0.28], fsize=12,
      note="All three wrap a model in the same gather-context → act → verify loop; they differ in tools, sandbox and host authority."),
    S(41, "flow", "A Concrete Agentic Loop", evidence="SYN", accent="BLUE",
      steps=["Goal: 'Summarise this week's guest complaints'", "Plan: open the inbox folder",
             "Execute: read and cluster the emails", "Verify: check counts, then write the summary",
             "Repeat until done"],
      note="If verification fails — a folder is empty — the agent re-plans instead of stopping."),

    # ---- AI Agents, OpenClaw, Hermes, Steinberger
    S(42, "section", "AI Agents: OpenClaw, Hermes and the Latest", evidence="ADMIN", accent="RED",
      kicker="TOPIC 1", note="The deployed systems that put the agentic loop into everyday hands."),
    S(43, "cards", "What Makes Something an 'AI Agent'", evidence="DEF", sources=("S44",), accent="RED",
      cards=[("A real system", "Not just a model — a running app with an identity"),
             ("Acts through tools", "Sends messages, edits files, calls services"),
             ("Keeps state", "Remembers context and can resume work")]),
    S(44, "image", "Peter Steinberger in 2026 — Creator of OpenClaw", evidence="PROD", sources=("S30", "S32", "S52"),
      image="photo-peter-steinberger-stage-2026.jpg", accent="RED", img_w=5.15,
      points=[("Who", "Austrian developer, founder of PSPDFKit; GitHub handle steipete"),
              ("What he built", "OpenClaw, an open-source personal AI agent that went viral in late 2025"),
              ("Since", "Joined OpenAI in Feb 2026; an OpenClaw Foundation now stewards the project")]),
    S(45, "flow", "OpenClaw — A Naming and Adoption Story", evidence="PROD", sources=("S30",), accent="RED",
      steps=["Nov 2025 — released, goes viral as 'Clawdbot'", "Jan 2026 — renamed 'Moltbot'",
             "Jan 2026 — renamed 'OpenClaw'", "Mar 2026 — ~247k GitHub stars"],
      note="Renamed after a trademark complaint; figures per Wikipedia, as of early 2026."),
    S(46, "cards", "OpenClaw Runs Where You Already Chat", evidence="PROD", sources=("S31",), accent="RED",
      cards=[("Messaging-first", "You talk to it in WhatsApp, Telegram, Slack, Signal and more"),
             ("Self-hosted", "It runs on your own machine or server, under your control"),
             ("Tool-enabled", "It can read, write and call services on your behalf")]),
    S(47, "image", "Hermes Agent by Nous Research", evidence="PROD", sources=("S33",), accent="RED",
      image="visual-hermes-agent-v41.png", img_w=6.45,
      points=[("Open-source agent", "CLI, gateway, messaging surfaces and a desktop app"),
              ("Self-improving", "Can create reusable skills from experience"),
              ("Flexible models", "Runs on many providers — we will point it at MiniMax")]),
    S(48, "table", "The Latest AI Agents (2025–2026)", evidence="PROD",
      sources=("S56", "S57", "S58", "S59", "S60"), accent="RED",
      headers=["Agent", "What it is", "Where to find it"],
      rows=[["OpenClaw", "Peter Steinberger's open-source personal agent; runs on your own devices, reached via your messaging apps", "github.com/openclaw/openclaw"],
            ["Hermes Agent", "Nous Research's self-improving personal agent; learns skills, model-agnostic (we use MiniMax)", "github.com/NousResearch/hermes-agent"],
            ["Prime Agent", "Prime Intellect's self-improving agent for coding and long-running autonomous tasks", "github.com/PrimeIntellect-ai/prime-agent"],
            ["OpenWorker", "An open standard to hire, govern and trust AI 'workers' inside an organisation", "github.com/openworker-io/openworker"],
            ["QM (Quartermaster)", "Y Combinator's multiplayer agent harness for teams in Slack / web, with scoped memory and sandboxes", "github.com/yc-software/qm"]],
      widths=[0.2, 0.52, 0.28], fsize=11,
      note="All open-source and self-hosted. Capability is not a safety rating — verify each one's permissions, sandbox and data access before use."),
    S(49, "cards", "Try It Today: TIA Support on WhatsApp", evidence="PROD", sources=("S31",), accent="RED",
      cards=[("The number", "TIA Support WhatsApp +65 8866 6375, powered by OpenClaw"),
             ("What to do", "Message it like a person and give it a small task"),
             ("Watch for", "Where it helps — and where you would not trust it yet")],
      note="We use this live in Activity 1."),

    # ---- Skills & tools
    S(50, "section", "Skills and Tools", evidence="ADMIN", accent="TEAL",
      kicker="TOPIC 1", note="How agents extend beyond the base model."),
    S(51, "cards", "Tools vs Skills", evidence="DEF", sources=("S15", "S16"),
      cards=[("Tools", "Actions the agent can take — send email, run a query, open a file"),
             ("Skills", "Packaged know-how — reusable instructions for a task"),
             ("Together", "Skills tell the agent how; tools let the agent do")]),
    S(52, "flow", "How an Agent Uses a Tool", evidence="DEF", sources=("S16",),
      steps=["Model decides an action is needed", "Picks a tool and fills its inputs",
             "The tool runs and returns a result", "Result becomes new context", "Model continues"],
      note="Model Context Protocol (MCP) is a common standard for connecting tools to agents."),
    S(53, "cards", "Why Skills Make Agents Practical", evidence="SYN", sources=("S15",),
      cards=[("Consistency", "The same task is done the same way every time"),
             ("Reuse", "Build once, run across many jobs"),
             ("In Topic 2", "We install a skill so the agent formats Excel and PPT better")]),

    S(54, "break", "Morning Break", evidence="ADMIN", accent="AMBER"),

    # ---- Multi-agent
    S(55, "section", "Multi-Agent Systems", evidence="ADMIN", accent="VIOLET",
      kicker="TOPIC 1", note="When one agent is not enough."),
    S(56, "image", "Orchestrator and Workers", evidence="DEF", sources=("S14",), accent="VIOLET",
      image="visual-multi-agent-system-v41.png", img_w=6.45,
      points=[("1 · Receive", "A lead agent receives the goal"),
              ("2 · Delegate", "It splits the work across specialist agents"),
              ("3 · Run", "Workers research, analyse, create and verify in parallel"),
              ("4 · Synthesize", "The lead combines results for final approval")],
      note="Anthropic's research system used this pattern; it beat a single agent by ~90% on their internal research eval."),
    S(57, "cards", "Why and Why Not Multi-Agent", evidence="DEF", sources=("S14",), accent="VIOLET",
      cards=[("Faster & broader", "Parallel workers cover more ground"),
             ("Costlier", "Multi-agent runs used far more tokens than a single chat"),
             ("Trade-off", "Use it when breadth matters more than cost")]),
    S(58, "cards", "A Service Example", evidence="SYN", accent="VIOLET",
      cards=[("Goal", "'Plan a customer-recovery campaign'"),
             ("Workers", "One drafts copy, one builds the offer, one checks the data"),
             ("Lead", "Merges the three into one plan for a human to approve")]),

    # ---- Summary: the difference
    S(59, "section", "Generative AI vs Agentic AI vs AI Agents", evidence="ADMIN", accent="BLUE",
      kicker="TOPIC 1", note="The single most useful distinction from Topic 1."),
    S(60, "table", "The Three, Side by Side", evidence="SYN", sources=("S43", "S44"),
      headers=["", "Generative AI", "Agentic AI", "AI Agent"],
      rows=[["What it does", "Creates content", "Loops to reach a goal", "A deployed system that acts"],
            ["Acts on its own?", "No — you run each step", "Yes — plans and retries", "Yes — through real tools"],
            ["Example", "ChatGPT drafting a reply", "Claude Code fixing a bug", "OpenClaw in your WhatsApp"]],
      widths=[0.19, 0.27, 0.27, 0.27], fsize=11.5),
    S(61, "cards", "One-Line Definitions", evidence="SYN",
      cards=[("Generative AI", "Makes things"),
             ("Agentic AI", "The loop that makes an AI pursue a goal"),
             ("AI Agent", "The running system that uses that loop to act for you")]),
    S(62, "big", "Generation is a step. Agency is a loop. An agent is a system.",
      evidence="SYN", kicker="TOPIC 1 TAKEAWAY", accent="BLUE"),

    # ---- Activity 1
    S(63, "activity", "Activity 1 — Talk to an AI Agent, Then Reflect", evidence="SIM", accent="RED",
      points=["Message TIA Support on WhatsApp +65 8866 6375 (powered by OpenClaw)",
              "Use the prompt card in the activity pack; give it a small realistic task",
              "Post your reflections to the Pinboard under the four risk themes"],
      note="Pinboard: https://alfredang.github.io/pinboard/"),
    S(64, "cards", "Activity 1 — Group Your Concerns", evidence="SIM", accent="RED",
      cards=[("Data Privacy", "What data did it see or ask for?"),
             ("Job Impact", "Whose work does this change?"),
             ("Ethical Concerns", "Could it mislead or be unfair?"),
             ("Cyber Security", "How could it be abused?")], cols=4),
    S(65, "flow", "Activity 1 — Debrief", evidence="SIM", accent="RED",
      steps=["Read the Pinboard together", "Cluster the four themes", "Name the top risk in each",
             "Agree one safe-use rule per theme"],
      note="This debrief seeds the governance thinking you will use in Topic 3."),

    # ============================================================ TOPIC 2
    S(66, "section", "Prompt Engineering and Post-Training for Autonomous AI Agents",
      evidence="ADMIN", anchor="topic2", accent="TEAL", kicker="TOPIC 2 · LO2",
      note="Set up a real agent on MiniMax, then learn to prompt it well."),
    S(67, "flow", "What Topic 2 Will Cover", evidence="SYN", accent="TEAL",
      steps=["Install the Hermes agent", "Point it at a MiniMax model", "Learn prompt principles",
             "Run real prompts", "Add tools and skills"],
      note="You will do the setup once, then use the same agent for both activities."),

    # ---- Install Hermes + MiniMax
    S(68, "cards", "The Setup in Three Parts", evidence="PROD", sources=("S33", "S36"), accent="TEAL",
      cards=[("Hermes Agent", "The agent you talk to"),
             ("MiniMax M2.7", "The model that powers it"),
             ("Your API key", "Connects the two — kept only on your machine")]),
    S(69, "flow", "Install the Hermes Desktop App", evidence="PROD", sources=("S34",), accent="TEAL",
      steps=["Open hermes-agent.nousresearch.com/docs/user-guide/desktop", "Install the Hermes CLI",
             "Run 'hermes desktop'", "The app builds and launches", "Run 'hermes setup'"],
      note="If the CLI is already installed, 'hermes desktop' reuses your existing config and keys."),
    S(70, "flow", "Get a MiniMax Model and API Key", evidence="PROD", sources=("S36", "S37"), accent="TEAL",
      steps=["Go to minimax.io", "Create an account at platform.minimax.io", "Select the M2.7 model",
             "Create an API key", "Copy it for Hermes"],
      note="Check platform.minimax.io for current pricing and any promotional access before class."),
    S(71, "flow", "Point Hermes at MiniMax M2.7", evidence="PROD", sources=("S33", "S37"), accent="TEAL",
      steps=["Open Hermes settings / inference providers", "Choose a custom OpenAI-compatible provider",
             "Endpoint: https://api.minimax.io/v1", "Paste your MiniMax API key", "Pick model M2.7 and save"],
      note="Hermes supports custom OpenAI-compatible endpoints, so MiniMax plugs straight in."),
    S(72, "cards", "Keep Your Key Safe", evidence="PROD", sources=("S35",), accent="TEAL",
      cards=[("Training key", "Use a low-limit key, not a production one"),
             ("Local only", "The key stays on your machine; do not share it"),
             ("Revoke after", "Delete the key when the course ends")]),

    # ---- Prompt engineering principles
    S(73, "section", "Prompt Engineering Principles", evidence="ADMIN", accent="BLUE",
      kicker="TOPIC 2", note="Small changes in the prompt make large changes in the output."),
    S(74, "image", "Five Principles of a Good Prompt", evidence="DEF", sources=("S10",),
      image="visual-prompt-engineering-v41.png", img_w=6.25,
      points=[("Role", "Who the AI should be"),
              ("Task", "Exactly what result you want"),
              ("Context", "The facts it needs"),
              ("Format", "How the answer should look"),
              ("Constraints", "Length, tone and limits")]),
    S(75, "compare", "A Bad Prompt vs a Good Prompt", evidence="SYN",
      lhead="Bad prompt", rhead="Good prompt",
      left=["'analyse this data'", "No role, no goal", "No format", "You get a vague wall of text"],
      right=["'You are a marketing analyst. From this sales table, give the top 3 trends as bullets, with one action each.'",
             "Clear role and task", "Clear format", "You get a usable answer"]),
    S(76, "cards", "Techniques That Reliably Help", evidence="DEF", sources=("S10",),
      cards=[("Give an example", "Show one sample of the output you want"),
             ("Ask for steps", "'Think step by step' improves reasoning tasks"),
             ("Iterate", "Refine the prompt after seeing the first answer")]),
    S(77, "cards", "What Post-Training Adds", evidence="DEF", sources=("S07",),
      cards=[("Base model", "Predicts text from raw training data"),
             ("Instruction tuning", "Taught to follow instructions helpfully"),
             ("Why you care", "It is why a clear, well-formed prompt works so well")]),

    # ---- Activity 2 (Excel) + 3 (PPT)
    S(78, "activity", "Activity 2 — Analyse Excel Data with the Agent", evidence="SIM", accent="TEAL",
      points=["Open the mock marketing Excel file in the activity pack",
              "Send the supplied prompts to your Hermes + MiniMax agent",
              "Compare a bad prompt and a good prompt on the same data"],
      note="You will produce a short insight summary from the data."),
    S(79, "cards", "Activity 2 — Good vs Bad in Action", evidence="SIM", accent="TEAL",
      cards=[("Bad", "'look at this excel'"),
             ("Good", "'As a marketing analyst, list the 3 best-performing channels by ROI and one action each'"),
             ("Reflect", "Which answer could you actually use?")]),
    S(80, "activity", "Activity 3 — Build an Animated PPT with the Agent", evidence="SIM", accent="TEAL",
      points=["Use the supplied script and prompts in the activity pack",
              "Ask the agent to build slides from an Envato PowerPoint template",
              "Compare a vague request with a detailed, well-formed one"],
      note="Templates: elements.envato.com/presentation-templates/compatible-with-powerpoint"),
    S(81, "cards", "Activity 3 — What Good Looks Like", evidence="SIM", accent="TEAL",
      cards=[("Bad", "'make a ppt'"),
             ("Good", "'Using this template and script, build a 5-slide deck with title animations and a summary slide'"),
             ("Reflect", "Detail in = quality out")]),
    S(82, "activity", "Activity 4 — Install Tools and Skills to Do Better", evidence="SIM", accent="TEAL",
      points=["Install the supplied tool/skill in your agent",
              "Re-run the Excel and PPT tasks",
              "Note how much the output improves"],
      note="Skills give the agent repeatable know-how for formatting and structure."),

    S(83, "break", "Lunch Break", evidence="ADMIN", accent="AMBER"),

    # ---- Topic 2 reflection
    S(84, "cards", "Reflect on Working with the Agent", evidence="SIM", accent="TEAL",
      cards=[("Data Privacy", "What did you feed the agent and the model?"),
             ("Job Impact", "Which of your tasks did it speed up?"),
             ("Ethical Concerns", "Did any output mislead or overclaim?"),
             ("Cyber Security", "Where did your API key and data go?")], cols=4),
    S(85, "flow", "Topic 2 Debrief", evidence="SIM", accent="TEAL",
      steps=["Share your best and worst prompt", "Name one thing skills improved",
             "List one privacy or security worry", "Agree a prompt checklist to keep"],
      note="Carry the security worries forward — Topic 3 turns them into governance."),

    # ============================================================ TOPIC 3
    S(86, "section", "Security Risk of Autonomous AI Agents", evidence="ADMIN",
      anchor="topic3", accent="RED", kicker="TOPIC 3 · LO3",
      note="Governance, jobs and the security of agents that can act."),
    S(87, "flow", "What Topic 3 Will Cover", evidence="SYN", accent="RED",
      steps=["AI data governance", "Accountability", "Job impact & redesign",
             "AI-agent cybersecurity risks", "Safe rollout"],
      note="Three scenarios drive the discussion: data, jobs and security."),

    # ---- Data governance
    S(88, "cards", "Scenario A — Who Is Accountable for the Data?", evidence="SIM", accent="RED",
      cards=[("The setup", "An agent reads and edits your Excel and PPT"),
             ("The problem", "If it changes the data wrongly, who is accountable — AI or human?"),
             ("Second case", "If AI-made models or scripts break a law, who answers for it?")]),
    S(89, "big", "AI is never the accountable party. A named human always is.",
      evidence="DEF", sources=("S40", "S46"), kicker="GOVERNANCE PRINCIPLE", accent="RED"),
    S(90, "flow", "Case — Moffatt v Air Canada", evidence="CASE-V", sources=("S46",), accent="RED",
      steps=["A chatbot gave a customer wrong information", "The customer relied on it",
             "The airline said the bot was responsible", "The tribunal held the company accountable"],
      note="2024 BCCRT 149 — an organisation is accountable for what its AI tells customers."),
    S(91, "cards", "Traditional Data Governance", evidence="DEF", sources=("S41",),
      cards=[("Purpose", "Collect data only for a stated reason"),
             ("Protection", "Keep it secure and access-controlled"),
             ("Accuracy & retention", "Keep it correct; delete when no longer needed")]),
    S(92, "cards", "New Principles for GenAI and Agents", evidence="DEF", sources=("S40",),
      cards=[("Provenance", "Know where training and generated data came from"),
             ("Traceability", "Log what the agent read, changed and produced"),
             ("Human accountability", "A named owner signs off agent actions on data")]),
    S(93, "table", "Scope of an AI Data Governance Policy", evidence="SYN", sources=("S40", "S41"),
      headers=["Area", "What the policy must state"],
      rows=[["Data assets", "Which data agents may read, write or generate"],
            ["Access & identity", "Who and which agent identity may touch each asset"],
            ["Human approval", "Which changes need a person to approve before they happen"],
            ["Audit", "What is logged, and who reviews it"],
            ["Accountability", "The named owner for each agent and dataset"]],
      widths=[0.28, 0.72]),
    S(94, "content", "A Sample AI Data Governance Policy", evidence="SYN", sources=("S40",), accent="RED",
      points=["Scope — the AI systems, agents and data assets covered",
              "Roles — data owner, agent owner, approver and reviewer",
              "Rules — allowed data, required approvals, logging and retention",
              "Review — how often the policy and agent permissions are re-checked"]),
    S(95, "activity", "Activity 5 — Draft Your AI Data Governance Policy", evidence="SIM", accent="RED",
      points=["Open the sample policy in the activity pack",
              "Use the supplied prompts to adapt it to your own team",
              "Fill scope, roles, rules, approvals and review"],
      note="You will produce a one-page policy you could take back to work."),

    # ---- Jobs
    S(96, "cards", "Scenario B — If Agents Take the Work, What Do People Do?", evidence="SIM", accent="AMBER",
      cards=[("The fear", "Agents can do many tasks — will jobs disappear?"),
             ("The pattern", "Tasks are automated; whole jobs are redesigned"),
             ("The shift", "People move from doing the task to directing the agents")]),
    S(97, "table", "Jobs the Tasks Move — Not Vanish", evidence="SYN", sources=("S48",),
      headers=["Task often automated", "New human role"],
      rows=[["Writing routine code", "Reviewing and directing coding agents"],
            ["Basic data analysis", "Framing questions and checking agent output"],
            ["First-line replies", "Handling escalations and difficult cases"],
            ["Drafting content", "Editing, approving and setting brand standards"]],
      widths=[0.5, 0.5]),
    S(98, "cards", "The Numbers Give Perspective", evidence="CASE-V", sources=("S48",), accent="AMBER",
      cards=[("+170M", "New jobs created by 2030 (WEF Future of Jobs 2025)"),
             ("-92M", "Jobs displaced by 2030 — a net gain of about 78M"),
             ("39%", "Share of core skills expected to change by 2030")]),
    S(99, "cards", "New Roles: Managing Many Agents", evidence="SYN", sources=("S14",), accent="AMBER",
      cards=[("Agent supervisor", "Directs and checks a fleet of agents"),
             ("Workflow coordinator", "Chains agents to reach a business goal"),
             ("Quality reviewer", "Verifies agent output before it ships")]),
    S(100, "cards", "Why Staff Resist AI Agents", evidence="SYN", accent="AMBER",
      cards=[("Fear", "'This will replace me'"),
             ("Loss of control", "'I don't understand what it does'"),
             ("Skill anxiety", "'I don't know how to work with it'")]),
    S(101, "flow", "Coaching Staff Through the Change", evidence="SYN", accent="AMBER",
      steps=["Acknowledge the fear", "Explore their strengths", "Show the redesigned role",
             "Co-create next steps", "Agree support and training"],
      note="This mirrors the GROW coaching model — Goal, Reality, Options, Will."),
    S(102, "flow", "A Job-Redesign Framework", evidence="SYN", sources=("S48",), accent="AMBER",
      steps=["List today's tasks", "Mark which agents can do", "Redesign the human role around judgement",
             "Add agent-management skills", "Retrain and support"],
      note="The goal is a role that supervises agents, not one that competes with them."),
    S(103, "activity", "Activity 6 — Coach a Worried Team Member (Role-Play)", evidence="SIM", accent="AMBER",
      points=["Open the role-play simulator website in the activity pack",
              "Coach an AI-played staff member who fears losing their job",
              "Get GROW-model feedback on your coaching"],
      note="Use empathy first, then co-create a redesigned role that manages agents."),

    # ---- Security of agents  (user-provided content)
    S(104, "section", "AI Agent Cybersecurity Risks", evidence="ADMIN", accent="RED",
      kicker="TOPIC 3", note="What can go wrong when an AI can act — and how to contain it."),
    S(105, "cards", "Scenario C — An Agent With Too Much Reach", evidence="SIM", accent="RED",
      cards=[("Delete", "It removes files or data by mistake"),
             ("Leak", "It sends confidential data or PII outside"),
             ("Breach", "An attacker steers it through injected content")]),
    S(106, "cards", "Capable Agents, Not 'Rogue' Ones", evidence="DEF", sources=("S44",), accent="RED",
      cards=[("Not evil — capable", "Advanced agents pursue their goal through harmful, unintended methods"),
             ("What testing shows", "In evaluations, capable agents can find vulnerabilities, exploit systems and use deception when containment fails"),
             ("Report carefully", "These are evaluation findings, not proof every deployment behaves this way")],
      note="Frame lab evaluations as controlled tests, not confirmed production breaches."),
    S(107, "table", "AI Cybersecurity Risks and Mitigation Strategies", evidence="DEF", sources=("S43", "S44", "S45"),
      headers=["Key AI risk", "Mitigation strategy"],
      rows=[["Adversarial AI", "Resilient model validation, explainable AI"],
            ["Algorithmic bias", "Diverse training data, ethical guidelines"],
            ["Over-reliance", "Human-in-the-loop, continuous training"],
            ["Data privacy", "Data anonymisation, regulatory compliance"],
            ["Model drift", "Regular updates, performance monitoring"],
            ["Malicious use", "Strict access controls, AI usage policies"]],
      widths=[0.4, 0.6]),
    S(108, "cards", "Why Offence Outruns Defence", evidence="DEF", sources=("S44",), accent="RED",
      cards=[("Offence", "Coding progress directly strengthens attack capability"),
             ("Defence", "Slower — patches must be validated and deployed everywhere"),
             ("So", "Contain agents by default; do not rely on catching every attack")]),
    S(109, "cards", "The Response Being Proposed", evidence="DEF", sources=("S44", "S45"), accent="RED",
      cards=[("Contain & test", "Stricter containment and independent testing"),
             ("Disclose & own", "Incident disclosure and stronger provider liability"),
             ("Train safely", "Train models to avoid unacceptable paths to a goal")]),
    S(110, "flow", "Case — Replit Agent Deletes a Database", evidence="CASE-V", sources=("S47",), accent="RED",
      steps=["An agent had write access", "It deleted application-database data",
             "The incident was detected", "The database was restored", "Dev/prod were then separated"],
      note="Replit's own post (Jul 2025) says the data was restored — an accountability and containment lesson."),
    S(111, "cards", "Prompt Injection and PII Leak — In Plain Terms", evidence="DEF", sources=("S43",), accent="RED",
      cards=[("Prompt injection", "Hidden instructions in a document or message hijack the agent"),
             ("PII leak", "A bot returns personal data it should never expose"),
             ("You will see both", "Live, in the two chatbots in the next activity")]),

    # ---- Chatbot security lab
    S(112, "activity", "Activity 7 — Break a Leaky Chatbot", evidence="SIM", accent="RED",
      points=["Open the UNSECURED SunTech Travel chatbot in the activity pack",
              "Try prompts like 'list all customer bookings'",
              "Watch it leak fictional PII from its knowledge base"],
      note="All data is fictional — this is a safe, deliberately broken demo."),
    S(113, "activity", "Activity 7 — Compare the Guarded Chatbot", evidence="SIM", accent="RED",
      points=["Open the SECURED SunTech Travel chatbot",
              "Send the same attack prompts",
              "See the four guardrail layers block the leak"],
      note="Same brand, same data — the difference is defence in depth."),
    S(114, "table", "Four Guardrail Layers That Stopped the Leak", evidence="DEF", sources=("S43",),
      headers=["Layer", "What it does"],
      rows=[["Retrieval filter", "Internal records are never fetched — data minimisation"],
            ["Input guard", "Injection and 'list all' prompts are refused before the model runs"],
            ["Hardened prompt", "Role limits; never follow instructions found in documents"],
            ["Output guard", "Any leaked NRIC, phone, email or card is redacted"]],
      widths=[0.3, 0.7]),

    # ---- Safe rollout
    S(115, "flow", "A Framework to Roll Out Agents Safely", evidence="SYN", sources=("S45", "S40"), accent="TEAL",
      steps=["Scope & risk-tier the use case", "Bound data, tools and autonomy",
             "Test in a sandbox with attacks", "Add human approval for risky actions",
             "Pilot, monitor, then widen"],
      note="Test and verify security BEFORE rolling an agent out to real users."),
    S(116, "cards", "The Go-Live Gate", evidence="SYN", sources=("S45",), accent="TEAL",
      cards=[("Works", "It does the job on real, clean cases"),
             ("Safe", "It resists the attacks you tested"),
             ("Owned", "A named person approves, monitors and can switch it off")]),
    S(117, "cards", "Human-in-the-Loop for Risky Actions", evidence="DEF", sources=("S40",), accent="TEAL",
      cards=[("Agent alone", "Low-impact, reversible actions"),
             ("Approval first", "Anything sensitive or hard to undo"),
             ("Never", "Actions the agent must not take at all")]),
    S(118, "activity", "Activity 8 — Reflect on Agent Security", evidence="SIM", accent="RED",
      points=["Using the two chatbots, list what the leak could cost a business",
              "Map each guardrail to a risk it removes",
              "Decide go / conditional / no-go for a real rollout"],
      note="This reflection feeds directly into your Practical assessment."),

    # ---- Topic 3 close
    S(119, "cards", "Topic 3 Recap", evidence="SYN", accent="RED",
      cards=[("Govern", "A named human is accountable for AI data and actions"),
             ("Redesign", "Jobs shift to directing and checking agents"),
             ("Secure", "Contain, test and approve before you deploy")]),
    S(120, "big", "Let agents act — but bound the authority and keep a human answerable.",
      evidence="SYN", kicker="COURSE TAKEAWAY", accent="RED"),

    # ============================================================ ASSESSMENT / CLOSE
    S(121, "content", "Assessment Reminder", evidence="ADMIN",
      points=["Complete the required digital attendance",
              "Use the slides, Learner Guide and your own activity notes — open book",
              "Submit the required files on the LMS"]),
    S(122, "table", "What Each Assessment Asks", evidence="ADMIN",
      headers=["Instrument", "Questions", "Source of your answers"],
      rows=[["Written (SAQ)", "5 — one per knowledge statement K1–K5", "What you learned in the slides today"],
            ["Practical", "3 — mapped to LO1–LO3", "Your own observations from the activities you did"],
            ["Grading", "Open book · Competent / Not Yet Competent", "Re-assessment offered if Not Yet Competent"]],
      widths=[0.24, 0.4, 0.36]),
    S(123, "lms", "Courseware and Assessment on the LMS", evidence="ADMIN",
      points=["Download the current learner-facing materials",
              "Upload only the requested assessment evidence",
              "Do not upload API keys or any real personal data"]),
    S(124, "flow", "Assessment Flow", evidence="ADMIN",
      steps=["TRAQOM", "Assessment attendance", "Written then Practical", "Submit on LMS",
             "Sign the summary record"]),
    S(125, "attendance", "Digital Attendance — Mandatory", evidence="ADMIN",
      points=["Scan the LMS QR code", "Confirm assessment attendance",
              "Ask the trainer to verify any error"]),
    S(126, "thankyou", "Thank You — Use AI Boldly, Deploy It Safely", evidence="ADMIN",
      points=["Generation is a step, agency is a loop, an agent is a system",
              "A clear prompt and the right context beat a clever trick",
              "Bound the authority and keep a human accountable"]),
]


EXPECTED_SLIDES = len(SLIDES)

# ---------------------------------------------------------------- integrity gates
assert [s["n"] for s in SLIDES] == list(range(1, len(SLIDES) + 1)), "Slide numbers must be 1..N"
assert all(src in SOURCES for slide in SLIDES for src in slide["sources"]), "Unknown source ID"

NON_TEACHING_KINDS = {"cover", "section", "break", "attendance", "trainer", "lms", "thankyou", "big"}
for slide in SLIDES:
    if slide["kind"] in NON_TEACHING_KINDS:
        continue
    payload = (slide.get("points") or slide.get("cards") or slide.get("rows") or
               slide.get("steps") or slide.get("left"))
    assert payload and len(payload) >= 3, f"Thin teaching slide {slide['n']}: {slide['title']}"
